#!/usr/bin/env expect

# Launch the server
spawn timeout 10m torchrun --nproc_per_node 1 -m chitu \
    models=Qwen2-7B-Instruct \
    models.ckpt_dir=/home/share/models/Qwen2-7B-Instruct \
    infer.cache_type=paged \
    infer.max_reqs=2 \
    infer.max_seq_len=1024 \
    serve.host=127.0.0.1 \
    serve.port=21100
set pid [exp_pid]
puts "Launching sever, pid is $pid"

# Wait for the server to start
expect -timeout -1 "Uvicorn running on"

# Test the server
puts "Starting test..."
system python3 test/test_stream_response.py http://127.0.0.1:21100/v1/chat/completions 2 256

# Clean up
puts "Testing done. You may see some killing messages following, which is expected."
puts "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
system kill $pid
