#!/usr/bin/expect

# Launch the server
spawn grun timeout 10m torchrun --nproc_per_node 1 -m chitu models=Qwen2-7B-Instruct models.ckpt_dir=/home/share/models/Qwen2-7B-Instruct infer.cache_type=paged serve.host=127.0.0.1 serve.port=21100
set pid [exp_pid]
system echo "Launching sever, pid is $pid"

# Wait for the server to start
expect -timeout -1 "Uvicorn running on"

# Test the server
system echo "Starting test..."
system python benchmarks/benchmark_serving.py --model "qwen2-7b" --iterations 10 --seq-len 10 --warmup 3 --base-url http://127.0.0.1:21100 || exit 1

# Clean up
system echo "Testing done. You may see some killing messages following, which is expected."
system echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
system kill $pid
