# SPDX-FileCopyrightText: 2025 Qingcheng.AI
#
# SPDX-License-Identifier: Apache-2.0

"""
Data-Parallel Token Sender
Sends tokens generated by a DP group back to the Token Router
"""

import logging
import msgpack
import time
from typing import Any, Optional
from typing_extensions import override
import threading
import queue
import zmq
import os

from chitu.distributed.coordinator import get_endpoint
from chitu.global_vars import get_global_args
from chitu.metrics.prometheus_collector import inc_completed_requests, observe_ttft
from chitu.task import Task, UserRequest
from chitu.trace import Trace
from chitu.async_stream import AsyncDataStream

logger = logging.getLogger(__name__)


class DPTokenSender:
    """Token sender in DP mode, responsible for sending tokens to the Router"""

    def __init__(
        self, router_address: str = "tcp://localhost:29700", instance_id: int = 0
    ):
        self.router_address = router_address
        self.instance_id = instance_id
        self.socket = None
        self.context = None
        self._send_queue = None
        self._sender_thread = None
        self._started = False
        self._start_lock = threading.Lock()

        logger.info(
            f"DPTokenSender created: instance={instance_id}, router={router_address}"
        )

        self.request_token_cache: dict[str, list[int]] = {}
        self._chars_len: dict[str, int] = {}
        self._first_token_sent: set[str] = set()

    async def start(self):
        """Start token sender (initialize synchronous ZMQ socket and sender thread)"""
        with self._start_lock:
            if self._started:
                return
            self._init_socket()
            self._start_sender_thread()
            self._started = True
            logger.info(f"DPTokenSender started for instance {self.instance_id}")

    def _init_socket(self):
        """Initialize synchronous ZMQ socket"""
        if self.socket is not None:
            return

        self.context = zmq.Context.instance()
        self.socket = self.context.socket(zmq.PUSH)
        self.socket.setsockopt(zmq.LINGER, 0)
        # 提升缓冲与高水位，减少回压导致的阻塞
        sndhwm = int(os.getenv("DP_SND_HWM", "200000"))
        sndbuf = int(os.getenv("DP_SNDBUF", "4194304"))  # 4MB
        conflate = int(os.getenv("DP_CONFLATE", "0"))
        tcp_keepalive = int(os.getenv("DP_TCP_KEEPALIVE", "1"))
        self.socket.setsockopt(zmq.SNDHWM, sndhwm)
        self.socket.setsockopt(zmq.SNDBUF, sndbuf)
        self.socket.setsockopt(zmq.CONFLATE, conflate)
        self.socket.setsockopt(zmq.TCP_KEEPALIVE, tcp_keepalive)

        # Wait for the router token endpoint of this instance, then connect to it.
        launch_timeout = getattr(
            get_global_args().multi_inst.router, "launch_timeout", None
        )
        ip, port = get_endpoint(
            "router", f"token_port_{self.instance_id}", timeout=launch_timeout
        )
        router_addr = f"tcp://{ip}:{port}"
        self.socket.connect(router_addr)
        logger.info(f"[DPTokenSender] group={self.instance_id} connect={router_addr}")
        if self._send_queue is None:
            self._send_queue = queue.Queue()

    def _remove_request(self, request_id: str):
        self.request_token_cache.pop(request_id, None)
        self._chars_len.pop(request_id, None)
        self._first_token_sent.discard(request_id)

    def _start_sender_thread(self):
        # 避免重复启动多个发送线程（ZeroMQ socket 非线程安全）
        if self._sender_thread is not None and self._sender_thread.is_alive():
            return

        def _loop():
            while True:
                try:
                    data = self._send_queue.get()
                    if data is None:
                        break
                    # Attempt non-blocking send first, fallback to blocking
                    try:
                        self.socket.send(data, flags=zmq.DONTWAIT)
                    except zmq.Again:
                        # Socket full, use blocking send
                        self.socket.send(data, flags=0)
                except Exception:
                    logger.exception(
                        "DPTokenSender sender thread fatal error, exiting process"
                    )
                    os._exit(1)

        self._sender_thread = threading.Thread(target=_loop, daemon=True)
        self._sender_thread.start()

    def send_token(
        self,
        request_id: str,
        tokens: list[int],
        top_logprobs: Optional[list[float]] = None,
        top_token_idx: Optional[list[int]] = None,
        task: Task | None = None,  # Add task parameter to record ttft
    ):
        """Send a single token to the Router"""
        # Check if this is the first token and get prompt_len
        is_first_token = request_id not in self._first_token_sent
        if is_first_token:
            self._first_token_sent.add(request_id)

        data = dict(
            type="token",
            request_id=request_id,
            tokens=tokens,
            top_logprobs=top_logprobs,
            top_token_idx=top_token_idx,
            instance_id=self.instance_id,
            timestamp=time.time(),
        )

        # If first token and task provided, include prompt_len info
        if is_first_token and task is not None and task.req is not None:
            # Record TTFT metric
            _created_ts = getattr(task, "_pd_created_ts", None)
            if _created_ts is not None:
                observe_ttft(time.time() - _created_ts)
            logger.debug(
                f"DP Token Sender: [request {request_id}] first token, prompt_len={task.req.prompt_len}, tokens={tokens}"
            )
        self._send_data(data)

    def send_finish(
        self,
        request_id: str,
        finish_reason: str = "stop",
        num_hit_tokens: int = 0,
    ):
        """Send request finish signal"""
        # Clean up caches for this request
        self.send_token(request_id, [])
        self._remove_request(request_id)
        data = dict(
            type="finish",
            request_id=request_id,
            finish_reason=finish_reason,
            num_hit_tokens=num_hit_tokens,
            instance_id=self.instance_id,
            timestamp=time.time(),
        )

        self._send_data(data)

    def send_evict(self, request_id: str, num_hit_tokens: int = 0):
        """Send request evict signal"""
        # Clean up caches for this request
        self._remove_request(request_id)
        data = dict(
            type="evict",
            request_id=request_id,
            num_hit_tokens=num_hit_tokens,
            instance_id=self.instance_id,
            timestamp=time.time(),
        )

        self._send_data(data)

    def send_error(self, request_id: str, error_message: str):
        """Send error signal"""
        # Clean up caches for this request
        self._remove_request(request_id)
        data = dict(
            type="error",
            request_id=request_id,
            error_message=error_message,
            instance_id=self.instance_id,
            timestamp=time.time(),
        )

        self._send_data(data)

    def send_trace(self, trace: Trace):
        data = trace.dump()
        data["type"] = "trace"
        logger.warning(f"{data}")
        self._send_data(data)

    def _send_data(self, data: dict[str, Any]):
        """Send data to Router (enqueue; background thread will send)"""
        packed_data = msgpack.packb(data)
        if self._send_queue.full():
            logger.warning("DP Token Sender: send queue is full, dropping token")
            return
        self._send_queue.put(packed_data)

    def close(self):
        """Close connection"""
        if hasattr(self, "_send_queue") and self._send_queue is not None:
            try:
                self._send_queue.put_nowait(None)
            except queue.Full:
                logger.warning(
                    "DPTokenSender queue full during close; skipping sentinel"
                )
        if hasattr(self, "_sender_thread") and self._sender_thread.is_alive():
            self._sender_thread.join(timeout=1)

        if self.socket:
            self.socket.close(0)
            self.socket = None

        # do not term the shared context
        self.request_token_cache.clear()
        self._started = False
        logger.info(f"DPTokenSender closed for group {self.instance_id}")


class DPAsyncDataStream(AsyncDataStream):
    """DP Async Data Stream with integrated Token Sender capability"""

    @classmethod
    def build(cls, enable_thinking: bool, task: Task, token_sender: DPTokenSender):
        async_stream = cls(enable_thinking=enable_thinking)
        async_stream.task = task
        async_stream.token_sender = token_sender
        return async_stream

    @override
    def add_data(
        self,
        value: Optional[int],
        top_logprobs=None,
        top_token_idx=None,
        *,
        notify_server: bool = True,
    ):
        if value is not None and not self.stop_signal:
            request_id = self.task.req.request_id
            self.token_sender.send_token(
                request_id=request_id,
                tokens=[value],
                top_logprobs=top_logprobs,
                top_token_idx=top_token_idx,
            )
            logger.debug(
                f"[DPAsyncDataStream] Token sent successfully: {request_id} -> {value}"
            )

    @override
    def send_stop_signal(self, error: Optional[str] = None):
        if not self.stop_signal:
            self.stop_signal = True
            if self.task.req.save_trace_dir:
                self.token_sender.send_trace(self.task.req.trace_data)
            if self.task.req.finish_reason != "evicted":
                self.token_sender.send_finish(
                    self.task.req.request_id,
                    self.task.req.finish_reason,
                    self.task.req.num_hit_tokens,
                )
            del self.task


class DPTokenManager:
    """DP Token Manager: manages token sending for the whole DP group"""

    def __init__(self, instance_id: int, router_address: str = "tcp://localhost:29700"):
        self.instance_id = instance_id
        self.router_address = router_address
        self.token_sender = DPTokenSender(router_address, instance_id)

        logger.info(
            f"DPTokenManager created: group={instance_id}, router={router_address}"
        )

    async def start(self):
        """Start Token Manager"""
        await self.token_sender.start()
        logger.debug(f"DP Token Manager started for group {self.instance_id}")

    def wrap_task(self, task: Task) -> Task:
        """Wrap Task to enable token sending"""
        task.req.async_stream = DPAsyncDataStream.build(
            task.req.enable_thinking, task=task, token_sender=self.token_sender
        )

        logger.debug(f"Wrapped task {task.req.request_id} for DP token sending")
        return task

    async def send_error_for_request(self, request_id: str, error_message: str):
        """Send error for a specific request"""
        self.token_sender.send_error(request_id, error_message)

    def close(self):
        """Close manager"""
        self.token_sender.close()


# Global instances (one per DP group)
_dp_token_managers: dict[int, DPTokenManager] = {}


def close_dp_token_managers():
    """Close all DP token managers."""
    global _dp_token_managers

    for manager in list(_dp_token_managers.values()):
        try:
            manager.close()
        except Exception:
            logger.exception("Failed to close DP token manager")

    _dp_token_managers.clear()


def get_dp_token_manager(
    instance_id: int, router_address: str = "tcp://localhost:29700"
) -> DPTokenManager:
    """Get DP Token Manager instance"""
    global _dp_token_managers

    if instance_id not in _dp_token_managers:
        _dp_token_managers[instance_id] = DPTokenManager(instance_id, router_address)

    return _dp_token_managers[instance_id]


async def start_dp_token_manager(
    instance_id: int, router_address: str = "tcp://localhost:29700"
):
    """Start Token Manager for the specified DP group"""
    manager = get_dp_token_manager(instance_id, router_address)
    await manager.start()
    return manager
