# SPDX-FileCopyrightText: 2025 Qingcheng.AI
#
# SPDX-License-Identifier: Apache-2.0

"""
Data-Parallel Token Sender
Sends tokens generated by a DP group back to the Token Router
"""

import logging
import msgpack
import time
from typing import Any, Optional
import threading
import queue
import zmq
import os

from chitu.global_vars import get_global_args
from chitu.metrics.prometheus_collector import inc_completed_requests, observe_ttft
from chitu.task import Task

logger = logging.getLogger(__name__)


class DPTokenSender:
    """Token sender in DP mode, responsible for sending tokens to the Router"""

    def __init__(
        self, router_address: str = "tcp://localhost:29700", dp_group_id: int = 0
    ):
        self.router_address = router_address
        self.dp_group_id = dp_group_id
        self.socket = None
        self.context = None
        self._send_queue = None
        self._sender_thread = None
        self._started = False
        self._start_lock = threading.Lock()

        self.instance_id = id(self)
        logger.info(
            f"DPTokenSender created: group={dp_group_id}, instance_id={self.instance_id}, router={router_address}"
        )

        self.request_token_cache: dict[str, list[int]] = {}
        self._chars_len: dict[str, int] = {}
        self._first_token_sent: set[str] = set()

    async def start(self):
        """Start token sender (initialize synchronous ZMQ socket and sender thread)"""
        with self._start_lock:
            if self._started:
                return
            self._init_socket()
            self._start_sender_thread()
            self._started = True
            logger.info(f"DPTokenSender started for group {self.dp_group_id}")

    def _init_socket(self):
        """Initialize synchronous ZMQ socket"""
        if self.socket is not None:
            return

        self.context = zmq.Context.instance()
        self.socket = self.context.socket(zmq.PUSH)
        self.socket.setsockopt(zmq.LINGER, 0)
        # 提升缓冲与高水位，减少回压导致的阻塞
        sndhwm = int(os.getenv("DP_SND_HWM", "200000"))
        sndbuf = int(os.getenv("DP_SNDBUF", "4194304"))  # 4MB
        conflate = int(os.getenv("DP_CONFLATE", "0"))
        tcp_keepalive = int(os.getenv("DP_TCP_KEEPALIVE", "1"))
        self.socket.setsockopt(zmq.SNDHWM, sndhwm)
        self.socket.setsockopt(zmq.SNDBUF, sndbuf)
        self.socket.setsockopt(zmq.CONFLATE, conflate)
        self.socket.setsockopt(zmq.TCP_KEEPALIVE, tcp_keepalive)

        router_host = get_global_args().dp_config.router.host
        router_token_base_port = get_global_args().dp_config.router.token_port
        router_addr = self.router_address
        if router_host and router_token_base_port is not None:
            port = int(router_token_base_port) + int(self.dp_group_id)
            router_addr = f"tcp://{router_host}:{port}"
            logger.info(f"port: {port}, router_addr: {router_addr}")
        self.socket.connect(router_addr)
        logger.info(
            f"[DPTokenSender] group={self.dp_group_id} connect={router_addr} host_cfg={router_host} base_cfg={router_token_base_port}"
        )
        if self._send_queue is None:
            self._send_queue = queue.Queue(maxsize=10000)

    def _start_sender_thread(self):
        # 避免重复启动多个发送线程（ZeroMQ socket 非线程安全）
        if self._sender_thread is not None and self._sender_thread.is_alive():
            return

        def _loop():
            while True:
                try:
                    data = self._send_queue.get()
                    if data is None:
                        break
                    # Attempt non-blocking send first, fallback to blocking
                    try:
                        self.socket.send(data, flags=zmq.DONTWAIT)
                    except zmq.Again:
                        # Socket full, use blocking send
                        self.socket.send(data, flags=0)
                except Exception as e:
                    logger.error(f"DPTokenSender sender thread error: {e}")
                    time.sleep(0.01)

        self._sender_thread = threading.Thread(target=_loop, daemon=True)
        self._sender_thread.start()

    def send_token(
        self,
        request_id: str,
        token: Optional[int],
        top_logprobs: Optional[list[float]] = None,
        top_token_idx: Optional[list[int]] = None,
        task: Task | None = None,  # Add task parameter to record ttft
    ):
        """Send a single token to the Router"""
        # Check if this is the first token and get prompt_len
        is_first_token = request_id not in self._first_token_sent
        if is_first_token:
            self._first_token_sent.add(request_id)

        data = dict(
            type="token",
            request_id=request_id,
            token=token,
            top_logprobs=top_logprobs,
            top_token_idx=top_token_idx,
            scheduler_id=self.dp_group_id,
            timestamp=time.time(),
        )

        # If first token and task provided, include prompt_len info
        if is_first_token and task is not None and task.req is not None:
            # Record TTFT metric
            _created_ts = getattr(task, "_pd_created_ts", None)
            if _created_ts is not None:
                observe_ttft(time.time() - _created_ts)
            logger.debug(
                f"DP Token Sender: [request {request_id}] first token, prompt_len={task.req.prompt_len}, token={token}"
            )
        self._send_data(data)

    def send_finish(self, request_id: str, finish_reason: str = "stop"):
        """Send request finish signal"""
        # Clean up caches for this request
        self.send_token(request_id, None)
        self.request_token_cache.pop(request_id, None)
        self._chars_len.pop(request_id, None)
        self._first_token_sent.discard(request_id)
        data = {
            "type": "finish",
            "request_id": request_id,
            "finish_reason": finish_reason,
            "scheduler_id": self.dp_group_id,
            "timestamp": time.time(),
        }

        self._send_data(data)

    def send_error(self, request_id: str, error_message: str):
        """Send error signal"""
        # Clean up caches for this request
        self.request_token_cache.pop(request_id, None)
        self._chars_len.pop(request_id, None)
        self._first_token_sent.discard(request_id)
        data = {
            "type": "error",
            "request_id": request_id,
            "error": error_message,
            "scheduler_id": self.dp_group_id,
            "timestamp": time.time(),
        }

        self._send_data(data)

    def _send_data(self, data: dict[str, Any]):
        """Send data to Router (enqueue; background thread will send)"""
        packed_data = msgpack.packb(data)
        if self._send_queue.full():
            logger.warning("DP Token Sender: send queue is full, dropping token")
            return
        self._send_queue.put(packed_data)

    def close(self):
        """Close connection"""
        if hasattr(self, "_send_queue"):
            self._send_queue.put(None)
        if hasattr(self, "_sender_thread") and self._sender_thread.is_alive():
            self._sender_thread.join(timeout=1)

        if self.socket:
            self.socket.close(0)

        # do not term the shared context
        self.request_token_cache.clear()
        self._started = False
        logger.info(f"DPTokenSender closed for group {self.dp_group_id}")


class DPTaskWrapper:
    """DP Task wrapper with integrated Token Sender capability"""

    def __init__(self, original_task: Task, token_sender: DPTokenSender):
        self.original_task = original_task
        self.token_sender = token_sender
        self._finish_sent = False

        # Hook update_response_sync for token sending
        self._original_update_response_sync = original_task.update_response_sync
        original_task.update_response_sync = self._dp_update_response_sync

        # Hook update_decode_status for finish detection
        self._original_update_decode_status = original_task.update_decode_status
        original_task.update_decode_status = self._dp_update_decode_status

    def _dp_update_response_sync(self, token: int):
        """Override update_response_sync to also send token to Router"""
        self._original_update_response_sync(token)
        # Enqueue in order to keep relative order with finish
        self._send_token_to_router(token)

    def _dp_update_decode_status(self):
        """Override update_decode_status to detect finish and send signal"""
        result = self._original_update_decode_status()

        # Check if task just finished and we haven't sent finish yet
        if not self._finish_sent and self.original_task.need_remove():
            request_id = self.original_task.req.request_id
            finish_reason = self.original_task.req.finish_reason or "stop"
            self.token_sender.send_finish(request_id, finish_reason)
            self._finish_sent = True
            self.original_task.pd_exec_end_logged = True
            # Record completed request metric
            inc_completed_requests("decode")
            logger.debug(
                f"[PD_STAGE][decode.exec.end] req_id={request_id} finish_reason={finish_reason}"
            )
            logger.debug(f"[DPTaskWrapper] Finish signal sent: {request_id}")

        return result

    def _send_token_to_router(self, token: int):
        """Synchronously enqueue current token to Router sending queue (lightweight, keep order)"""
        request_id = self.original_task.req.request_id

        self.token_sender.send_token(
            request_id=request_id,
            token=token,
            top_logprobs=None,
            top_token_idx=None,
            task=self.original_task,
        )

        logger.debug(
            f"[DPTaskWrapper] Token sent successfully: {request_id} -> {token}"
        )

    def __getattr__(self, name):
        """Delegate other attributes to the original task"""
        return getattr(self.original_task, name)


class DPTokenManager:
    """DP Token Manager: manages token sending for the whole DP group"""

    def __init__(self, dp_group_id: int, router_address: str = "tcp://localhost:29700"):
        self.dp_group_id = dp_group_id
        self.router_address = router_address
        self.token_sender = DPTokenSender(router_address, dp_group_id)
        self.wrapped_tasks: dict[str, DPTaskWrapper] = {}

        self.instance_id = id(self)
        logger.info(
            f"DPTokenManager created: group={dp_group_id}, instance_id={self.instance_id}, router={router_address}"
        )

    async def start(self):
        """Start Token Manager"""
        await self.token_sender.start()
        logger.debug(f"DP Token Manager started for group {self.dp_group_id}")

    def wrap_task(self, task: Task) -> DPTaskWrapper:
        """Wrap Task to enable token sending"""
        if task.req.request_id in self.wrapped_tasks:
            return self.wrapped_tasks[task.req.request_id]

        wrapped = DPTaskWrapper(task, self.token_sender)
        self.wrapped_tasks[task.req.request_id] = wrapped

        logger.debug(f"Wrapped task {task.req.request_id} for DP token sending")
        return wrapped

    def unwrap_task(self, request_id: str):
        """Unwrap Task"""
        if request_id in self.wrapped_tasks:
            del self.wrapped_tasks[request_id]

    async def send_error_for_request(self, request_id: str, error_message: str):
        """Send error for a specific request"""
        await self.token_sender.send_error(request_id, error_message)

    def close(self):
        """Close manager"""
        self.token_sender.close()


# Global instances (one per DP group)
_dp_token_managers: dict[int, DPTokenManager] = {}


def get_dp_token_manager(
    dp_group_id: int, router_address: str = "tcp://localhost:29700"
) -> DPTokenManager:
    """Get DP Token Manager instance"""
    global _dp_token_managers

    if dp_group_id not in _dp_token_managers:
        _dp_token_managers[dp_group_id] = DPTokenManager(dp_group_id, router_address)

    return _dp_token_managers[dp_group_id]


async def start_dp_token_manager(
    dp_group_id: int, router_address: str = "tcp://localhost:29700"
):
    """Start Token Manager for the specified DP group"""
    manager = get_dp_token_manager(dp_group_id, router_address)
    await manager.start()
    return manager
