stages:
    - format
    - run

variables:
    VENV: "/home/hkz2/.venv/cinfer"

before_script:
    - source $VENV/bin/activate

format_check:
    stage: format
    only:
        - merge_requests
    tags:
        - chitu830-dev
    script:
        - black --exclude src/third_party/ --check .

run_check:
    stage: run
    only:
        - merge_requests
    tags:
        - chitu830-dev
    needs:
        - format_check
    script:
        - if [ -d "/home/hkz2/cinfer/src/third_party" ]; then cp -r /home/hkz2/cinfer/src/third_party/* ./src/third_party/; fi
        - source /home/spack/spack/share/spack/setup-env.sh
        - spack load cuda@12.4.0
        - TORCH_CUDA_ARCH_LIST=8.6 python setup.py build -j4 develop
        - grun torchrun --nproc_per_node 1 --master_port=22512 test/single_req_test.py request.max_new_tokens=64