stages:
    - format
    - env
    - check

variables:
    VENV: "/home/hkz2/.venv/cinfer"

before_script:
    - source $VENV/bin/activate

format_check:
    stage: format
    only:
        - merge_requests
    tags:
        - chitu830-dev
    script:
        - black --exclude src/third_party/ --exclude third_party/ --check .

env_build:
    stage: env
    only:
        - merge_requests
    tags:
        - chitu830-dev
    needs:
        - format_check
    script:
        - git submodule update --init --recursive
        - git submodule foreach --recursive git clean -ffdx
        - git submodule foreach --recursive git reset --hard
        - source /home/spack/spack/share/spack/setup-env.sh
        - spack load cuda@12.4.0
        - TORCH_CUDA_ARCH_LIST=8.6 CINFER_SETUP_JOBS=4 MAX_JOBS=4 CINFER_WITH_CYTHON=1 pip install --no-build-isolation -i https://pypi.tuna.tsinghua.edu.cn/simple .[quant]


paged_check:
    stage: check
    only:
        - merge_requests
    tags:
        - chitu830-dev
    needs:
        - env_build
    script:
        - grun torchrun --nproc_per_node 1 --master_port=22514 test/single_req_test.py request.max_new_tokens=64 infer.cache_type=paged


skew_check:
    stage: check
    only:
        - merge_requests
    tags:
        - chitu830-dev
    needs:
        - env_build
    script:
        - grun torchrun --nproc_per_node 1 --master_port=22515 test/single_req_test.py request.max_new_tokens=64 infer.cache_type=skew