stages:
    - format
    - env
    - check

variables:
    VENV: "/home/gitlab-runner/venv-cinfer-ci"

before_script:
    - |
      if [ ! -d "$VENV" ]; then
        python3 -m venv "$VENV"
      fi
    - source $VENV/bin/activate

format_check:
    stage: format
    only:
        - merge_requests
    tags:
        - maas-runner-a2
    script:
        - pip install black -i https://pypi.tuna.tsinghua.edu.cn/simple
        - black --exclude src/third_party/ --exclude third_party/ --check .

env_build_nvidia:
    stage: env
    only:
        - merge_requests
    tags:
        - maas-runner-a2
    needs:
        - format_check
    script:
        - git submodule update --init --recursive
        - git submodule foreach --recursive git clean -ffdx
        - git submodule foreach --recursive git reset --hard
        - source /home/spack/spack/share/spack/setup-env.sh
        - spack load cuda@12.4.0
        - pip install -r requirements-build.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
        - TORCH_CUDA_ARCH_LIST=8.6 CINFER_SETUP_JOBS=4 MAX_JOBS=4 CINFER_WITH_CYTHON=1 pip install --no-build-isolation -i https://pypi.tuna.tsinghua.edu.cn/simple .[quant]


env_build_muxi:
    stage: env
    only:
        - merge_requests
    tags:
        - muxi
    needs:
        - format_check
    script:
        - git submodule update --init --recursive
        - git submodule foreach --recursive git clean -ffdx
        - git submodule foreach --recursive git reset --hard
        - export PATH=/opt/maca/mxgpu_llvm/bin:/opt/maca/bin:$PATH
        - export MACA_PATH=/opt/maca
        - export LD_LIBRARY_PATH=/opt/maca/lib:/opt/maca/mxgpu_llvm/lib:$LD_LIBRARY_PATH
        - pip install -U /home/share/software/maca-pytorch2.1-py38-2.25.2.8-x86_64/2.25.2.8/wheel/*.whl -i https://pypi.tuna.tsinghua.edu.cn/simple
        - pip install -r requirements-build.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
        - CINFER_SETUP_JOBS=4 MAX_JOBS=4 CINFER_WITH_CYTHON=1 pip install --no-build-isolation -i https://pypi.tuna.tsinghua.edu.cn/simple .


paged_check_nvidia:
    stage: check
    only:
        - merge_requests
    tags:
        - maas-runner-a2
    needs:
        - env_build_nvidia
    script:
      - srun --gres=gpu:def:1 --mem=10G -p debug --pty torchrun --nproc_per_node 1 --master_port=22514 test/single_req_test.py request.max_new_tokens=64 infer.cache_type=paged


paged_check_muxi:
    stage: check
    only:
        - merge_requests
    tags:
        - muxi
    needs:
        - env_build_muxi
    script:
      - export PATH=/opt/maca/mxgpu_llvm/bin:/opt/maca/bin:$PATH
      - export MACA_PATH=/opt/maca
      - export LD_LIBRARY_PATH=/opt/maca/lib:/opt/maca/mxgpu_llvm/lib:$LD_LIBRARY_PATH
      - torchrun --nproc_per_node 1 --master_port=22514 test/single_req_test.py request.max_new_tokens=64 infer.cache_type=paged


skew_check_nvidia:
    stage: check
    only:
        - merge_requests
    tags:
        - maas-runner-a2
    needs:
        - env_build_nvidia
    script:
      - srun --gres=gpu:def:1 --mem=10G -p debug --pty torchrun --nproc_per_node 1 --master_port=22515 test/single_req_test.py request.max_new_tokens=64 infer.cache_type=skew


skew_check_muxi:
    stage: check
    only:
        - merge_requests
    tags:
        - muxi
    needs:
        - env_build_muxi
    script:
      - export PATH=/opt/maca/mxgpu_llvm/bin:/opt/maca/bin:$PATH
      - export MACA_PATH=/opt/maca
      - export LD_LIBRARY_PATH=/opt/maca/lib:/opt/maca/mxgpu_llvm/lib:$LD_LIBRARY_PATH
      - torchrun --nproc_per_node 1 --master_port=22515 test/single_req_test.py request.max_new_tokens=64 infer.cache_type=skew
