# SPDX-FileCopyrightText: 2025 Qingcheng.AI
#
# SPDX-License-Identifier: Apache-2.0

quant: 
- model: '.'
  rules:
    - regex: 'kv_b_proj'
    - regex: 'q_a_proj'
    - regex: 'kv_a_proj_with_mqa'
    - regex: 'q_b_proj'
      type: w8a8_per_token_per_channel_dyn
      kwargs:
        weight_scale_dtype: float32
        weight_scale_has_singleton_last_dim: True
    - regex: '\.self_attn'
      type: w8a8_per_token_per_channel_dyn
      kwargs:
        weight_scale_has_singleton_last_dim: True
    - regex: '\.mlp.moe'
      type: w8a8_per_token_per_channel_dyn
      kwargs:
        weight_scale_has_singleton_last_dim: True
    - regex: '\.mlp.experts\.'
      type: w8a8_per_token_per_channel_dyn
      kwargs:
        weight_scale_has_singleton_last_dim: True
    - regex: '\.mlp.shared_experts'
      type: w8a8_per_token_per_channel_dyn
      kwargs:
        weight_scale_has_singleton_last_dim: True
    - regex: '\.mlp.gate_proj'
      type: w8a8_per_token_per_channel_dyn
      kwargs:
        weight_scale_has_singleton_last_dim: True
    - regex: '\.mlp.gate_up_proj'
      type: w8a8_per_token_per_channel_dyn
      kwargs:
        weight_scale_has_singleton_last_dim: True
    - regex: '\.mlp.up_proj'
      type: w8a8_per_token_per_channel_dyn
      kwargs:
        weight_scale_has_singleton_last_dim: True
    - regex: '\.mlp.down_proj'
      type: w8a8_per_token_per_channel_dyn
      kwargs:
        weight_scale_has_singleton_last_dim: True
