quant: 
- model: '.'
  rules:
    - regex : '\.gate_proj$'
      type : blockfp4
    - regex : '\.gate$'
      type : blockfp8
      kwargs:
        block_size : 128
    - regex : '^layers\.'
      type : blockfp4