name: deepseek-r1-distill-qwen-14b
type: hf-llama
ckpt_dir: /home/share/models/DeepSeek-R1-Distill-Qwen-14B
tokenizer_path: /home/share/models/DeepSeek-R1-Distill-Qwen-14B # TODO
dim: 5120
n_layers: 48
n_heads: 40
n_kv_heads: 8
vocab_size: 152064
intermediate_dim: 13824
norm_eps: 1e-05
rope_theta: 1000000.0
max_position_embeddings: 131072
max_seq_len: 10240 # length of prefill + decode
rs_token_id: 151648
re_token_id: 151649
