name: qwen2-70b
type: qwen
ckpt_dir: /home/mnt/ss/models/Qwen2-7B-Instruct-CInfer/
tokenizer_path: /home/mnt/ss/models/Qwen2-7B-Instruct # TODO
dim: 8192
n_layers: 80
n_heads: 64
n_kv_heads: 8
vocab_size: 152064
intermediate_dim: 29568
norm_eps: 1e-06
rope_theta: 1000000.0
max_seq_len: 1024 # length of prefill + decode
