name: 使用问题
description: 使用此模版提交您的使用问题
title: "[Bug]: 您的标题"
labels: ["usage"]
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: |
        在提交问题以前，请确认该问题在没有在[issues](https://github.com/thu-pacman/chitu/issues)中被提出过。感谢您的贡献！
  - type: input
    id: contact
    attributes:
      label: 您的联系方式
      description: 若我们需要确认更多的信息，如何联系您？
      placeholder: eg.email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happend
    attributes:
      label: 问题描述
      description: 清楚准确的描述您希望如何运行该系统。
      placeholder: Tell us what you see!
      value: "此处输入您希望如何运行该系统"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: 版本信息
      description: 您运行的版本是?
      options:
        - 0.1.2 (Default)
        - 0.1.1
        - 0.1.0
      default: 0
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: 提交前请确认
      description: 提交报告以前，请搜索[issues](https://github.com/thu-pacman/chitu/issues)，确认该问题未提出过。
      options:
        - label: 确认
          required: true
