# SPDX-FileCopyrightText: 2026 Qingcheng.AI
#
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

import json
import os
import time
from logging import getLogger
from typing import (
    Annotated,
    Any,
    Literal,
    Optional,
)

from fastapi.responses import JSONResponse, StreamingResponse
from pydantic import BaseModel, ConfigDict, Field, model_validator

from chitu.serve.api_docs import DocField
from chitu.tool_call.type_def import ChoiceDelta, ChoiceToolCall, ToolConfig
from chitu.serve.request_id import gen_req_id

DOC_GENERATION = os.environ.get("CHITU_HTTP_API_DOCS") == "1"

if not DOC_GENERATION:
    from chitu.global_vars import get_global_args
    from chitu.task import UserRequest, RequestParams
    from chitu.tool_call import get_tool_parser_cls, parse_stream_by_parser
    from chitu.serve.anthropic_api import resolve_requested_model_or_error
    from chitu.serve.common import (
        build_chat_template_kwargs,
        submit_request,
    )

logger = getLogger(__name__)

# Model name prefixes whose chat template / encoder consumes reasoning_effort.
# Matching is prefix-based: "GLM-5.2" matches "GLM-5.2", "GLM-5.2-FP8", etc.
_REASONING_EFFORT_MODELS = ("GLM-5.2", "DeepSeek-V4")


class ResponsesStreamOptions(BaseModel):
    model_config = ConfigDict(extra="allow")
    include_obfuscation: bool | None = DocField(
        None,
        en="Accepted for OpenAI SDK compatibility and currently ignored.",
        zh="为兼容 OpenAI SDK 而接受，当前会被忽略。",
    )


class ResponsesReasoningConfig(BaseModel):
    model_config = ConfigDict(extra="allow")
    effort: str | None = DocField(
        None,
        en='Reasoning effort. The value "none" disables thinking; other values enable thinking and may be mapped for supported models.',
        zh='推理强度。"none" 会关闭 thinking；其他值会启用 thinking，并可能为受支持模型进行映射。',
    )
    summary: Any | None = DocField(
        None,
        en="Accepted for compatibility. Reasoning summaries are not generated by this endpoint.",
        zh="为兼容性而接受。该接口不会生成 reasoning summary。",
    )


class ResponsesTextFormat(BaseModel):
    model_config = ConfigDict(extra="allow")
    type: Literal["text", "json_object", "json_schema"] = DocField(
        "text",
        en='Text output format: "text", "json_object", or "json_schema".',
        zh='文本输出格式："text"、"json_object" 或 "json_schema"。',
    )
    name: str | None = DocField(
        None, en="Optional response format name.", zh="可选的响应格式名称。"
    )
    schema_: dict[str, Any] | None = DocField(
        None,
        en="JSON schema used when type is json_schema.",
        zh="type 为 json_schema 时使用的 JSON schema。",
        alias="schema",
        serialization_alias="schema",
    )
    description: str | None = DocField(
        None, en="Optional response format description.", zh="可选的响应格式说明。"
    )
    strict: bool | None = DocField(
        None,
        en="Whether strict schema adherence is requested.",
        zh="是否请求严格遵循 schema。",
    )


class ResponsesTextConfig(BaseModel):
    model_config = ConfigDict(extra="allow")
    format: ResponsesTextFormat | None = DocField(
        None,
        en="Text output format configuration.",
        zh="文本输出格式配置。",
    )
    verbosity: str | None = DocField(
        None,
        en="Optional verbosity hint accepted for compatibility.",
        zh="为兼容性接受的可选详细程度提示。",
    )


class ToolChoiceNamedTool(BaseModel):
    type: Literal["function"] = DocField(
        "function",
        en="Named function tool selector type.",
        zh="命名 function tool 选择器类型。",
    )
    name: str = DocField(
        en="Name of the function tool to select.", zh="要选择的 function tool 名称。"
    )


class ResponsesInputTextBlock(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["input_text", "text", "output_text", "reasoning_text"] = DocField(
        en="Text-like input content block type.",
        zh="文本类输入内容块类型。",
    )
    text: str = DocField(en="Text content.", zh="文本内容。")


class ResponsesInputImageBlock(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["input_image"] = DocField(
        "input_image",
        en="Image input content block. It is converted to a text placeholder by this endpoint.",
        zh="图片输入内容块。该接口会将其转换为文本占位符。",
    )
    file_id: str | None = DocField(
        None, en="Uploaded image file identifier.", zh="已上传图片文件 ID。"
    )
    image_url: str | dict[str, Any] | None = DocField(
        None, en="Image URL.", zh="图片 URL。"
    )


class ResponsesInputFileBlock(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["input_file"] = DocField(
        "input_file",
        en="File input content block. It is converted to a text placeholder by this endpoint.",
        zh="文件输入内容块。该接口会将其转换为文本占位符。",
    )
    filename: str | None = DocField(None, en="File name.", zh="文件名。")
    file_id: str | None = DocField(
        None, en="Uploaded file identifier.", zh="已上传文件 ID。"
    )
    file_url: str | None = DocField(None, en="File URL.", zh="文件 URL。")


ResponsesInputContentBlock = Annotated[
    ResponsesInputTextBlock | ResponsesInputImageBlock | ResponsesInputFileBlock,
    Field(discriminator="type"),
]


class ResponsesMessageInputItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["message"] = DocField(
        "message", en="Message input item.", zh="消息输入项。"
    )
    role: str = DocField(en="Message role.", zh="消息角色。")
    content: str | list[str | ResponsesInputContentBlock] = DocField(
        en="Message content as text or content blocks.",
        zh="消息内容，可以是文本或内容块。",
    )


class ResponsesFunctionCallInputItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["function_call"] = DocField(
        "function_call",
        en="Function call input item.",
        zh="函数调用输入项。",
    )
    call_id: str = DocField(en="Function call identifier.", zh="函数调用 ID。")
    name: str = DocField(en="Function name.", zh="函数名称。")
    arguments: str = DocField(
        "",
        en="Function call arguments as a JSON string.",
        zh="JSON 字符串形式的函数调用参数。",
    )


class ResponsesFunctionCallOutputInputItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["function_call_output"] = DocField(
        "function_call_output",
        en="Function call output input item.",
        zh="函数调用结果输入项。",
    )
    call_id: str = DocField(en="Function call identifier.", zh="函数调用 ID。")
    output: str | list[str | ResponsesInputContentBlock] = DocField(
        "",
        en="Function output as text or content blocks.",
        zh="函数输出，可以是文本或内容块。",
    )


class ResponsesReasoningInputItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["reasoning"] = DocField(
        "reasoning",
        en="Reasoning input item accepted for compatibility and ignored by this endpoint.",
        zh="为兼容性接受并由该接口忽略的 reasoning 输入项。",
    )


ResponsesInputItem = Annotated[
    ResponsesMessageInputItem
    | ResponsesFunctionCallInputItem
    | ResponsesFunctionCallOutputInputItem
    | ResponsesReasoningInputItem,
    Field(discriminator="type"),
]


def _model_to_dict(value):
    if isinstance(value, BaseModel):
        return value.model_dump(exclude_none=True)
    return value


class ResponsesCreateRequest(BaseModel):
    """
    Minimal subset of OpenAI Responses API.

    Unknown fields are accepted to stay compatible with current SDKs, but most of
    them are ignored unless explicitly handled below.
    """

    model_config = ConfigDict(extra="allow")
    model: Optional[str] = DocField(
        None,
        en="Model identifier. Defaults to the loaded model when omitted and supports configured model aliases.",
        zh="模型标识符。省略时默认使用已加载模型，并支持配置的模型别名。",
    )
    input: str | list[ResponsesInputItem | dict[str, Any]] | None = DocField(
        None,
        en="Input text or input items. Supported item types include messages, function_call, and function_call_output.",
        zh="输入文本或 input item 列表。支持 message、function_call 和 function_call_output 等 item 类型。",
    )
    instructions: Optional[str] = DocField(
        None,
        en="System or developer instructions prepended to the request.",
        zh="插入到请求前的系统或开发者指令。",
    )
    max_output_tokens: Optional[int] = DocField(
        None,
        en="Maximum number of tokens to generate. Uses the server default when omitted.",
        zh="最大生成 token 数。省略时使用服务端默认值。",
    )
    stream: bool = DocField(
        False,
        en="Whether to stream the response using Responses-style SSE events.",
        zh="是否使用 Responses 风格的 SSE 事件流返回响应。",
    )
    stream_options: ResponsesStreamOptions | None = DocField(
        None,
        en="Streaming options accepted for SDK compatibility.",
        zh="为兼容 SDK 而接受的流式选项。",
    )
    temperature: Optional[float] = DocField(
        None,
        en="Sampling temperature. Uses the server default when omitted.",
        zh="采样温度。省略时使用服务端默认值。",
    )
    top_p: Optional[float] = DocField(
        None,
        en="Nucleus sampling threshold. Uses the server default when omitted.",
        zh="核采样阈值。省略时使用服务端默认值。",
    )
    text: ResponsesTextConfig | None = DocField(
        None,
        en="Text output configuration, including text.format.",
        zh="文本输出配置，包括 text.format。",
    )
    reasoning: ResponsesReasoningConfig | None = DocField(
        None,
        en="Reasoning configuration. reasoning.effort='none' disables thinking; other values are treated as enabled.",
        zh="推理配置。reasoning.effort='none' 会关闭 thinking；其他值会视为开启。",
    )
    tools: list[dict[str, Any]] = DocField(
        default_factory=list,
        en="Function tools. Both Responses-style flat function tools and Chat Completions-style nested function tools are accepted.",
        zh="函数工具。既支持 Responses 风格的扁平 function tool，也支持 Chat Completions 风格的嵌套 function tool。",
    )
    tool_choice: Literal["none", "auto", "required"] | ToolChoiceNamedTool = DocField(
        "auto",
        en='Tool choice behavior: "auto", "none", "required", or a named function tool.',
        zh='工具选择行为："auto"、"none"、"required"，或指定一个命名 function tool。',
    )
    parallel_tool_calls: bool = DocField(
        True,
        en="Whether the model can make multiple tool calls in parallel.",
        zh="模型是否可以并行发起多个工具调用。",
    )
    previous_response_id: Optional[str] = DocField(
        None,
        en="Unsupported. Requests setting this field are rejected.",
        zh="暂不支持。设置该字段的请求会被拒绝。",
    )
    store: bool = DocField(
        False,
        en="Unsupported when true. Requests with store=true are rejected.",
        zh="为 true 时暂不支持。store=true 的请求会被拒绝。",
    )
    conversation: Optional[str | dict[str, Any]] = DocField(
        None,
        en="Unsupported. Requests setting this field are rejected.",
        zh="暂不支持。设置该字段的请求会被拒绝。",
    )
    metadata: dict[str, Any] = DocField(
        default_factory=dict,
        en="Arbitrary metadata echoed back in the response.",
        zh="原样回显到响应里的任意元数据。",
    )
    ttft_timeout_s: Optional[float] = DocField(
        None,
        en="Time-to-first-token timeout in seconds. Requests that wait too long to satisfy their TTFT requirement can be terminated to leave capacity for other requests that may still return in time.",
        zh="首 token 延迟超时时间，单位为秒。若请求等待过久且已无法满足 TTFT 要求，可终止该请求以便为仍可能及时返回的其他请求留出处理能力。",
    )

    @model_validator(mode="after")
    def validate_minimal_supported_shape(self):
        if self.input is None:
            raise ValueError("input is required")
        if self.stream and self.stream_options is None:
            self.stream_options = ResponsesStreamOptions()
        return self

    @property
    def resolved_temperature(self) -> float:
        return self.temperature if self.temperature is not None else 0.8

    @property
    def resolved_top_p(self) -> float:
        return self.top_p if self.top_p is not None else 0.9


def responses_error(status_code: int, error_type: str, message: str):
    return JSONResponse(
        status_code=status_code,
        content={
            "error": {
                "message": message,
                "type": error_type,
                "param": None,
                "code": None,
            }
        },
    )


def _sse_event(event: str, data: dict[str, Any]) -> str:
    return f"event: {event}\ndata: {json.dumps(data, ensure_ascii=False)}\n\n"


def _placeholder_for_image_block(block: dict[str, Any]) -> str:
    if block.get("file_id"):
        return f"[input_image omitted: file_id={block['file_id']}]"
    if block.get("image_url"):
        return "[input_image omitted: image_url]"
    return "[input_image omitted]"


def _placeholder_for_file_block(block: dict[str, Any]) -> str:
    if block.get("filename"):
        return f"[input_file omitted: {block['filename']}]"
    if block.get("file_id"):
        return f"[input_file omitted: file_id={block['file_id']}]"
    if block.get("file_url"):
        return "[input_file omitted: file_url]"
    return "[input_file omitted]"


def flatten_response_content(
    content: str | list[str | ResponsesInputContentBlock],
) -> str:
    if isinstance(content, str):
        return content

    parts: list[str] = []
    for item in content:
        item = _model_to_dict(item)
        if isinstance(item, str):
            parts.append(item)
            continue
        if not isinstance(item, dict):
            raise ValueError("Invalid content block type")
        block_type = item.get("type")
        if block_type in {"input_text", "text", "output_text", "reasoning_text"}:
            parts.append(str(item.get("text", "")))
            continue
        if block_type == "input_image":
            parts.append(_placeholder_for_image_block(item))
            continue
        if block_type == "input_file":
            parts.append(_placeholder_for_file_block(item))
            continue
        raise ValueError(f"Unsupported content block type: {block_type}")
    return "\n".join(part for part in parts if part)


def normalize_response_tools(
    tools: list[dict[str, Any]],
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    internal_tools: list[dict[str, Any]] = []
    public_tools: list[dict[str, Any]] = []
    for tool in tools:
        if "function" in tool:
            fn = tool["function"]
            tool_type = tool.get("type")
            if tool_type not in {None, "function"}:
                raise ValueError(f"Unsupported tool type: {tool_type}")
            name = fn.get("name", "")
            description = fn.get("description", "")
            parameters = fn.get("parameters") or {}
            strict = tool.get("strict", fn.get("strict"))
        else:
            tool_type = tool.get("type")
            if tool_type != "function":
                raise ValueError(f"Unsupported tool type: {tool_type}")
            name = tool.get("name", "")
            description = tool.get("description", "")
            parameters = tool.get("parameters") or {}
            strict = tool.get("strict")

        if not name:
            raise ValueError("Tool name is required")

        internal_tools.append(
            {
                "type": "function",
                "function": {
                    "name": name,
                    "description": description,
                    "parameters": parameters,
                },
            }
        )
        public_tool = {
            "type": "function",
            "name": name,
            "description": description,
            "parameters": parameters,
        }
        if strict is not None:
            public_tool["strict"] = strict
        public_tools.append(public_tool)
    return internal_tools, public_tools


def normalize_text_config(
    text_config: ResponsesTextConfig | None,
) -> tuple[dict[str, Any], dict[str, Any] | None]:
    normalized = {"format": {"type": "text"}}
    internal_response_format = None
    if text_config is None or text_config.format is None:
        return normalized, None

    format_dict = text_config.format.model_dump(exclude_none=True, by_alias=True)
    normalized["format"] = format_dict
    if text_config.verbosity is not None:
        normalized["verbosity"] = text_config.verbosity

    format_type = format_dict.get("type", "text")
    if format_type == "text":
        return normalized, None
    if format_type in {"json_object", "json_schema"}:
        internal_response_format = format_dict
        return normalized, internal_response_format
    raise ValueError(f"Unsupported text.format type: {format_type}")


def responses_input_to_internal(
    input_value: str | list[ResponsesInputItem | dict[str, Any]]
) -> list[dict[str, Any]]:
    if isinstance(input_value, str):
        return [{"role": "user", "content": input_value}]

    results: list[dict[str, Any]] = []
    pending_tool_calls: list[dict[str, Any]] = []

    def flush_tool_calls():
        if not pending_tool_calls:
            return
        results.append(
            {
                "role": "assistant",
                "content": "",
                "tool_calls": list(pending_tool_calls),
            }
        )
        pending_tool_calls.clear()

    for item in input_value:
        item = _model_to_dict(item)
        if not isinstance(item, dict):
            raise ValueError("Each input item must be an object")

        item_type = item.get("type")
        if item_type == "function_call":
            call_id = item.get("call_id")
            name = item.get("name")
            if not call_id or not name:
                raise ValueError("function_call requires call_id and name")
            pending_tool_calls.append(
                {
                    "id": call_id,
                    "type": "function",
                    "function": {
                        "name": name,
                        "arguments": str(item.get("arguments", "")),
                    },
                }
            )
            continue

        flush_tool_calls()

        if item_type == "function_call_output":
            call_id = item.get("call_id")
            if not call_id:
                raise ValueError("function_call_output requires call_id")
            output = item.get("output", "")
            if isinstance(output, str):
                output_text = output
            else:
                output_text = flatten_response_content(output)
            results.append(
                {"role": "tool", "tool_call_id": call_id, "content": output_text}
            )
            continue

        if item_type == "reasoning":
            continue

        if item_type == "message" or "role" in item:
            role = item.get("role")
            if not role:
                raise ValueError("message item requires role")
            results.append(
                {
                    "role": role,
                    "content": flatten_response_content(item.get("content", "")),
                }
            )
            continue

        raise ValueError(f"Unsupported input item type: {item_type}")

    flush_tool_calls()
    return results


def build_internal_messages(request: ResponsesCreateRequest) -> list[dict[str, Any]]:
    internal_messages = responses_input_to_internal(request.input)
    _, response_format = normalize_text_config(request.text)
    if request.instructions is None and response_format is None:
        return internal_messages

    control_message: dict[str, Any] = {
        "role": "system",
        "content": request.instructions or "",
    }
    if response_format is not None:
        control_message["response_format"] = response_format
    return [control_message, *internal_messages]


def enable_thinking_from_request(request: ResponsesCreateRequest) -> bool:
    if request.reasoning is None or request.reasoning.effort is None:
        return True
    return request.reasoning.effort != "none"


def reasoning_effort_from_request(request: ResponsesCreateRequest) -> Optional[str]:
    if request.reasoning is None or request.reasoning.effort is None:
        return None
    effort = request.reasoning.effort
    if effort == "none":
        return None
    # Only GLM-5.2 and DeepSeek-V4 templates/encoders consume reasoning_effort.
    # Other models silently ignore the kwarg, but we return None early to avoid
    # passing a meaningless value.
    model_name = get_global_args().models.name
    if not any(model_name.startswith(prefix) for prefix in _REASONING_EFFORT_MODELS):
        return None
    # Both templates recognise exactly two tiers:
    #   "high"  -> lighter reasoning  (GLM: "Reasoning Effort: High")
    #   "max"   -> heavier reasoning  (GLM: "Reasoning Effort: Max", default)
    # Map OpenAI's ascending five-value scale monotonically onto those two tiers.
    if effort in ("low", "medium"):
        return "high"
    return "max"


def _make_message_item(item_id: str, text: str) -> dict[str, Any]:
    return {
        "id": item_id,
        "type": "message",
        "status": "completed",
        "role": "assistant",
        "content": [
            {
                "type": "output_text",
                "text": text,
                "annotations": [],
            }
        ],
    }


def _make_function_call_item(
    *,
    item_id: str,
    call_id: str,
    name: str,
    arguments: str,
) -> dict[str, Any]:
    return {
        "id": item_id,
        "type": "function_call",
        "call_id": call_id,
        "name": name,
        "arguments": arguments,
        "status": "completed",
    }


def _update_tool_buffer(
    tool_buffers: dict[int, dict[str, str]],
    tool_call: ChoiceToolCall,
    *,
    track_started: bool,
) -> dict[str, str]:
    default_buffer = {"id": tool_call.id or "", "name": "", "arguments": ""}
    if track_started:
        default_buffer["started"] = ""

    buf = tool_buffers.setdefault(tool_call.index, default_buffer)
    if tool_call.id:
        buf["id"] = tool_call.id
    if tool_call.function.name:
        buf["name"] += tool_call.function.name
    if tool_call.function.arguments:
        buf["arguments"] += tool_call.function.arguments
    return buf


def _stream_source_for_response(
    req: UserRequest,
):
    if not req.tool_call_params:
        return req.async_stream

    parser_cls = get_tool_parser_cls()
    parser = parser_cls(req.tool_call_params.tools)
    return parse_stream_by_parser(req.async_stream, parser)


def _response_status_and_incomplete_details(
    req: UserRequest,
) -> tuple[str, dict[str, Any] | None]:
    if req.finish_reason == "length":
        return "incomplete", {"reason": "max_output_tokens"}
    return "completed", None


def _response_usage(req: UserRequest) -> dict[str, Any]:
    completion_tokens = req.async_stream.tokens_len
    prompt_tokens = req.prompt_len
    cached_tokens = req.num_hit_tokens
    return {
        "input_tokens": prompt_tokens,
        "input_tokens_details": {"cached_tokens": cached_tokens},
        "output_tokens": completion_tokens,
        "output_tokens_details": {"reasoning_tokens": 0},
        "total_tokens": prompt_tokens + completion_tokens,
        "cached_token": cached_tokens,
    }


def _build_response_skeleton(
    *,
    request: ResponsesCreateRequest,
    response_model: str,
    response_id: str,
    public_tools: list[dict[str, Any]],
    public_tool_choice: str | dict[str, Any],
    status: str,
    created_at: int,
    output: list[dict[str, Any]],
    usage: dict[str, Any] | None,
    incomplete_details: dict[str, Any] | None,
    output_text: str | None = None,
    completed_at: int | None = None,
) -> dict[str, Any]:
    text_config, _response_format = normalize_text_config(request.text)
    response = {
        "id": response_id,
        "object": "response",
        "created_at": created_at,
        "status": status,
        "error": None,
        "incomplete_details": incomplete_details,
        "instructions": request.instructions,
        "max_output_tokens": request.max_output_tokens,
        "model": response_model,
        "output": output,
        "parallel_tool_calls": request.parallel_tool_calls,
        "previous_response_id": None,
        "reasoning": {
            "effort": request.reasoning.effort if request.reasoning else None,
            "summary": None,
        },
        "store": False,
        "temperature": request.resolved_temperature,
        "text": text_config,
        "tool_choice": public_tool_choice,
        "tools": public_tools,
        "top_p": request.resolved_top_p,
        "truncation": "disabled",
        "usage": usage,
        "user": None,
        "metadata": request.metadata,
    }
    if completed_at is not None:
        response["completed_at"] = completed_at
    if output_text is not None:
        response["output_text"] = output_text
    return response


def _build_message_item_started_event(
    *,
    text_item_id: str,
) -> list[str]:
    return [
        _sse_event(
            "response.output_item.added",
            {
                "type": "response.output_item.added",
                "output_index": 0,
                "item": {
                    "id": text_item_id,
                    "type": "message",
                    "status": "in_progress",
                    "role": "assistant",
                    "content": [],
                },
            },
        ),
        _sse_event(
            "response.content_part.added",
            {
                "type": "response.content_part.added",
                "item_id": text_item_id,
                "output_index": 0,
                "content_index": 0,
                "part": {
                    "type": "output_text",
                    "text": "",
                    "annotations": [],
                },
            },
        ),
    ]


def _build_message_item_done_events(
    *,
    text_item_id: str,
    output_text: str,
) -> tuple[dict[str, Any], list[str]]:
    message_item = _make_message_item(text_item_id, output_text)
    return message_item, [
        _sse_event(
            "response.output_text.done",
            {
                "type": "response.output_text.done",
                "item_id": text_item_id,
                "output_index": 0,
                "content_index": 0,
                "text": output_text,
            },
        ),
        _sse_event(
            "response.content_part.done",
            {
                "type": "response.content_part.done",
                "item_id": text_item_id,
                "output_index": 0,
                "content_index": 0,
                "part": message_item["content"][0],
            },
        ),
        _sse_event(
            "response.output_item.done",
            {
                "type": "response.output_item.done",
                "output_index": 0,
                "item": message_item,
            },
        ),
    ]


def _build_function_call_started_event(
    *,
    item_id: str,
    call_id: str,
    name: str,
    output_index: int,
) -> str:
    return _sse_event(
        "response.output_item.added",
        {
            "type": "response.output_item.added",
            "output_index": output_index,
            "item": {
                "id": item_id,
                "type": "function_call",
                "call_id": call_id,
                "name": name,
                "arguments": "",
                "status": "in_progress",
            },
        },
    )


def _build_function_call_done_events(
    *,
    function_item: dict[str, Any],
    output_index: int,
) -> list[str]:
    return [
        _sse_event(
            "response.function_call_arguments.done",
            {
                "type": "response.function_call_arguments.done",
                "item_id": function_item["id"],
                "output_index": output_index,
                "arguments": function_item["arguments"],
                "name": function_item["name"],
            },
        ),
        _sse_event(
            "response.output_item.done",
            {
                "type": "response.output_item.done",
                "output_index": output_index,
                "item": function_item,
            },
        ),
    ]


async def collect_response_output(
    *,
    req: UserRequest,
) -> tuple[str, list[dict[str, Any]]]:
    output_text_parts: list[str] = []
    tool_buffers: dict[int, dict[str, str]] = {}

    if req.tool_call_params:
        stream = _stream_source_for_response(req)
        async for data, _is_reasoning, _extra in stream:
            if not data or not isinstance(data, ChoiceDelta):
                continue
            if data.content:
                output_text_parts.append(data.content)
            for tool_call in data.tool_calls or []:
                _update_tool_buffer(tool_buffers, tool_call, track_started=False)
    else:
        async for data, is_reasoning, _extra in req.async_stream:
            if not data or is_reasoning:
                continue
            output_text_parts.append(data)

    output_items: list[dict[str, Any]] = []
    output_text = "".join(output_text_parts)
    if output_text:
        output_items.append(_make_message_item(f"msg_{req.request_id}", output_text))
    for index in sorted(tool_buffers):
        buf = tool_buffers[index]
        call_id = buf["id"] or f"call_{gen_req_id()}"
        output_items.append(
            _make_function_call_item(
                item_id=f"fc_{call_id}",
                call_id=call_id,
                name=buf["name"],
                arguments=buf["arguments"],
            )
        )
    return output_text, output_items


def build_responses_response(
    *,
    request: ResponsesCreateRequest,
    response_model: str,
    user_req: UserRequest,
    output_text: str,
    output_items: list[dict[str, Any]],
    public_tools: list[dict[str, Any]],
    public_tool_choice: str | dict[str, Any],
) -> dict[str, Any]:
    created_at = int(time.time())
    status, incomplete_details = _response_status_and_incomplete_details(user_req)
    return _build_response_skeleton(
        request=request,
        response_model=response_model,
        response_id=f"resp_{user_req.request_id}",
        public_tools=public_tools,
        public_tool_choice=public_tool_choice,
        status=status,
        created_at=created_at,
        completed_at=created_at,
        output=output_items,
        output_text=output_text,
        usage=_response_usage(user_req),
        incomplete_details=incomplete_details,
    )


async def responses_stream_from_async_stream(
    *,
    user_req: UserRequest,
    request: ResponsesCreateRequest,
    response_model: str,
    public_tools: list[dict[str, Any]],
    public_tool_choice: str | dict[str, Any],
):
    response_id = f"resp_{user_req.request_id}"
    output_text_parts: list[str] = []
    tool_buffers: dict[int, dict[str, str]] = {}

    for event_name in ("response.created", "response.in_progress"):
        yield _sse_event(
            event_name,
            {
                "type": event_name,
                "response": _build_response_skeleton(
                    request=request,
                    response_model=response_model,
                    response_id=response_id,
                    public_tools=public_tools,
                    public_tool_choice=public_tool_choice,
                    status="in_progress",
                    created_at=int(time.time()),
                    output=[],
                    usage=None,
                    incomplete_details=None,
                ),
            },
        )

    stream = _stream_source_for_response(user_req)

    text_item_id = f"msg_{user_req.request_id}"
    text_started = False
    async for data, is_reasoning, _extra in stream:
        if not data:
            continue
        if public_tools and isinstance(data, ChoiceDelta):
            if data.content:
                if not text_started:
                    text_started = True
                    for event in _build_message_item_started_event(
                        text_item_id=text_item_id
                    ):
                        yield event
                output_text_parts.append(data.content)
                yield _sse_event(
                    "response.output_text.delta",
                    {
                        "type": "response.output_text.delta",
                        "item_id": text_item_id,
                        "output_index": 0,
                        "content_index": 0,
                        "delta": data.content,
                    },
                )
            for tool_call in data.tool_calls or []:
                buf = _update_tool_buffer(tool_buffers, tool_call, track_started=True)
                call_id = buf["id"] or f"call_{gen_req_id()}"
                item_id = f"fc_{call_id}"
                output_index = tool_call.index + (1 if text_started else 0)
                if not buf["started"]:
                    buf["started"] = "1"
                    yield _build_function_call_started_event(
                        item_id=item_id,
                        call_id=call_id,
                        name=buf["name"],
                        output_index=output_index,
                    )
                if tool_call.function.arguments:
                    yield _sse_event(
                        "response.function_call_arguments.delta",
                        {
                            "type": "response.function_call_arguments.delta",
                            "item_id": item_id,
                            "output_index": output_index,
                            "delta": tool_call.function.arguments,
                        },
                    )
            continue

        if is_reasoning:
            continue
        if not text_started:
            text_started = True
            for event in _build_message_item_started_event(text_item_id=text_item_id):
                yield event
        output_text_parts.append(data)
        yield _sse_event(
            "response.output_text.delta",
            {
                "type": "response.output_text.delta",
                "item_id": text_item_id,
                "output_index": 0,
                "content_index": 0,
                "delta": data,
            },
        )

    output_items: list[dict[str, Any]] = []
    output_text = "".join(output_text_parts)
    if text_started:
        message_item, done_events = _build_message_item_done_events(
            text_item_id=text_item_id, output_text=output_text
        )
        for event in done_events:
            yield event
        output_items.append(message_item)

    for index in sorted(tool_buffers):
        buf = tool_buffers[index]
        call_id = buf["id"] or f"call_{gen_req_id()}"
        output_index = index + (1 if text_started else 0)
        function_item = _make_function_call_item(
            item_id=f"fc_{call_id}",
            call_id=call_id,
            name=buf["name"],
            arguments=buf["arguments"],
        )
        for event in _build_function_call_done_events(
            function_item=function_item, output_index=output_index
        ):
            yield event
        output_items.append(function_item)

    yield _sse_event(
        "response.completed",
        {
            "type": "response.completed",
            "response": build_responses_response(
                request=request,
                response_model=response_model,
                user_req=user_req,
                output_text=output_text,
                output_items=output_items,
                public_tools=public_tools,
                public_tool_choice=public_tool_choice,
            ),
        },
    )


async def handle_responses_request(
    *,
    request: ResponsesCreateRequest,
    priority: int,
):
    try:
        response_model = resolve_requested_model_or_error(request.model)
        internal_tools, public_tools = normalize_response_tools(request.tools)
        if isinstance(request.tool_choice, ToolChoiceNamedTool):
            tool_config = ToolConfig(
                "required",
                request.parallel_tool_calls,
                [request.tool_choice.name],
            )
            public_tool_choice = request.tool_choice.model_dump()
        else:
            tool_config = ToolConfig(
                request.tool_choice, not request.parallel_tool_calls
            )
            public_tool_choice = request.tool_choice
        internal_messages = build_internal_messages(request)
    except ValueError as e:
        return responses_error(400, "invalid_request_error", str(e))

    if request.previous_response_id is not None:
        return responses_error(
            400,
            "invalid_request_error",
            "previous_response_id is not supported yet",
        )
    if request.store:
        return responses_error(
            400,
            "invalid_request_error",
            "store=true is not supported yet",
        )
    if request.conversation is not None:
        return responses_error(
            400,
            "invalid_request_error",
            "conversation is not supported yet",
        )

    args = get_global_args()
    enable_thinking = enable_thinking_from_request(request)
    chat_template_kwargs = build_chat_template_kwargs(
        enable_thinking, reasoning_effort_from_request(request)
    )

    req_params = RequestParams(
        messages=internal_messages,
        request_id=gen_req_id(),
        tools=internal_tools,
        tool_config=tool_config,
        logprobs=False,
        top_logprobs=None,
        max_new_tokens=request.max_output_tokens or args.request.max_new_tokens,
        temperature=request.resolved_temperature,
        top_p=request.resolved_top_p,
        top_k=50,
        frequency_penalty=0.0,
        chat_template_kwargs=chat_template_kwargs,
        enable_thinking=enable_thinking,
        save_trace_dir=args.debug.save_trace_dir,
        priority=priority,
        stop_with_eos=True,
        ttft_timeout_s=request.ttft_timeout_s,
    )
    user_req = UserRequest.from_request_params(req_params)
    await submit_request(user_req)

    if request.stream:
        return StreamingResponse(
            responses_stream_from_async_stream(
                user_req=user_req,
                request=request,
                response_model=response_model,
                public_tools=public_tools,
                public_tool_choice=public_tool_choice,
            ),
            media_type="text/event-stream",
        )

    output_text, output_items = await collect_response_output(req=user_req)
    return JSONResponse(
        build_responses_response(
            request=request,
            response_model=response_model,
            user_req=user_req,
            output_text=output_text,
            output_items=output_items,
            public_tools=public_tools,
            public_tool_choice=public_tool_choice,
        )
    )
