# SPDX-FileCopyrightText: 2025 Qingcheng.AI
#
# SPDX-License-Identifier: Apache-2.0

import threading
import logging
from typing import Optional
from chitu.backend import Backend
from chitu.utils import get_local_ip, get_free_port
from prometheus_client import Counter, Gauge, start_http_server, REGISTRY
import atexit
from chitu.distributed.parallel_state import get_dp_group
import torch

logger = logging.getLogger(__name__)


class PrometheusMetricsCollector:
    """Singleton metrics collector for Prometheus"""

    _instance: Optional["PrometheusMetricsCollector"] = None
    _lock = threading.RLock()
    _shutting_down = False  # 正在关闭为True，未关闭和关闭完成为False

    @classmethod
    def get_instance(cls, is_create: bool = False):
        if cls._shutting_down:
            return None

        if cls._instance is not None:
            return cls._instance

        if not is_create:
            return None

        with cls._lock:
            if cls._instance is None:
                dp_id = get_dp_group().rank_in_group
                rank = get_dp_group().global_rank
                cls._instance = cls(rank, dp_id)
        return cls._instance

    def __init__(self, rank, dp_id):
        self.rank = rank
        self.dp_id = dp_id
        self.total_generated_tokens: Optional[Counter] = None
        self.total_prompt_tokens: Optional[Counter] = None
        self.total_task_evictions: Optional[Counter] = None
        self.kv_cache_usage: Optional[Gauge] = None
        self.used_blocks: Optional[Gauge] = None
        self.total_blocks: Optional[Gauge] = None
        self.total_bytes: Optional[Gauge] = None
        self.used_bytes: Optional[Gauge] = None
        self.torch_allocated_bytes: Optional[Gauge] = None
        self.collector_server = None
        self.collector_thread = None
        self.addr = None

        try:
            self.total_generated_tokens = Counter(
                "chitu_total_generated_tokens",
                "Total tokens generated by executor",
                ["rank", "dp_id"],
            )
            self.total_prompt_tokens = Counter(
                "chitu_total_prompt_tokens",
                "Total prompt tokens processed by executor",
                ["rank", "dp_id"],
            )
            self.total_task_evictions = Counter(
                "chitu_total_task_evictions",
                "Total number of tasks evicted due to insufficient KV cache",
                ["rank", "dp_id"],
            )
            self.kv_cache_usage = Gauge(
                "chitu_kv_cache_usage_ratio",
                "KV cache usage ratio (used_blocks / total_blocks)",
                ["rank", "dp_id"],
            )
            self.used_blocks = Gauge(
                "chitu_used_blocks",
                "KV cache used blocks",
                ["rank", "dp_id"],
            )
            self.total_blocks = Gauge(
                "chitu_total_blocks",
                "KV cache total blocks",
                ["rank", "dp_id"],
            )
            self.total_bytes = Gauge(
                "chitu_total_bytes",
                "GPU total memory (bytes)",
                ["rank", "dp_id"],
            )
            self.used_bytes = Gauge(
                "chitu_used_bytes",
                "GPU used memory (bytes)",
                ["rank", "dp_id"],
            )
            self.torch_allocated_bytes = Gauge(
                "chitu_torch_allocated_bytes",
                "torch allocated GPU used memory (bytes)",
                ["rank", "dp_id"],
            )
            self.total_generated_tokens.labels(rank=rank, dp_id=dp_id).inc(0)
            self.total_prompt_tokens.labels(rank=rank, dp_id=dp_id).inc(0)
            self.total_task_evictions.labels(rank=rank, dp_id=dp_id).inc(0)
            self.kv_cache_usage.labels(rank=rank, dp_id=dp_id).set(0)
            self.used_blocks.labels(rank=rank, dp_id=dp_id).set(0)
            self.total_blocks.labels(rank=rank, dp_id=dp_id).set(0)
            self.total_bytes.labels(rank=rank, dp_id=dp_id).set(0)
            self.used_bytes.labels(rank=rank, dp_id=dp_id).set(0)
            self.torch_allocated_bytes.labels(rank=rank, dp_id=dp_id).set(0)
            try:
                ip = get_local_ip()
            except Exception:
                ip = "127.0.0.1"
            port = get_free_port()
            self.collector_server, self.collector_thread = start_http_server(
                port
            )  # Prometheus serve pull data from this server
            self.addr = f"{ip}:{port}"
            logger.info(f"Prometheus metrics server started on addr {self.addr}")
            atexit.register(PrometheusMetricsCollector.stop_instance)

        except Exception as e:
            logger.error(f"Failed to start Prometheus metrics server: {e}")
            raise

    @classmethod
    def inc_generated_tokens(cls, count: int = 1):
        if count < 0:
            return

        collector = cls.get_instance()
        if not collector:
            return
        try:
            collector.total_generated_tokens.labels(
                rank=collector.rank, dp_id=collector.dp_id
            ).inc(count)
        except Exception as e:
            logger.error(f"inc_generated_tokens failed: {e}")

    @classmethod
    def inc_prompt_tokens(cls, count: int = 1):
        if count < 0:
            return

        collector = cls.get_instance()
        if not collector:
            return
        try:
            collector.total_prompt_tokens.labels(
                rank=collector.rank, dp_id=collector.dp_id
            ).inc(count)
        except Exception as e:
            logger.error(f"inc_prompt_tokens failed: {e}")

    @classmethod
    def update_kvcache_usage(cls):
        """Update KV cache usage metrics."""
        if Backend.cache_manager is None:
            return

        cls.update_GPU_usage()

        collector = cls.get_instance()
        if not collector:
            return

        try:
            num_blocks = Backend.cache_manager.get_num_blocks()
            num_used_blocks = Backend.cache_manager.num_used_blocks

            collector.total_blocks.labels(
                rank=collector.rank, dp_id=collector.dp_id
            ).set(num_blocks)
            collector.used_blocks.labels(
                rank=collector.rank, dp_id=collector.dp_id
            ).set(num_used_blocks)

            if num_blocks > 0:
                usage_ratio = num_used_blocks / num_blocks
                collector.kv_cache_usage.labels(
                    rank=collector.rank, dp_id=collector.dp_id
                ).set(usage_ratio)
            else:
                logger.error(
                    f"Unexpected {type(Backend.cache_manager).__name__}.num_blocks({num_blocks}), update_kvcache_usage failed. "
                )
        except Exception as e:
            logger.error(f"update_kvcache_usage failed: {e}")
            pass

    @classmethod
    def update_GPU_usage(cls):
        if Backend.cache_manager is None:
            return

        collector = cls.get_instance()
        if not collector:
            return

        try:
            device = Backend.cache_manager.device
            if (not isinstance(device, torch.device)) or (
                isinstance(device, torch.device) and device.type != "cuda"
            ):
                return

            free_bytes, total_bytes = torch.cuda.mem_get_info(device)
            torch_allocated = torch.cuda.memory_allocated(device)
            collector.total_bytes.labels(
                rank=collector.rank, dp_id=collector.dp_id
            ).set(total_bytes)
            collector.used_bytes.labels(rank=collector.rank, dp_id=collector.dp_id).set(
                total_bytes - free_bytes
            )
            collector.torch_allocated_bytes.labels(
                rank=collector.rank, dp_id=collector.dp_id
            ).set(torch_allocated)

        except Exception as e:
            logger.error(f"update_GPU_usage failed: {e}")
            pass

    @classmethod
    def inc_task_eviction(cls):
        """Increment task eviction counter"""
        collector = cls.get_instance()
        if not collector:
            return

        try:
            collector.total_task_evictions.labels(
                rank=collector.rank, dp_id=collector.dp_id
            ).inc()
        except Exception as e:
            logger.error(f"inc_task_eviction failed: {e}")
            pass

    @classmethod
    def stop_instance(cls):
        cls._shutting_down = True
        with cls._lock:
            if cls._instance is None:
                return

            instance = cls._instance
            try:
                # Stop HTTP server
                if instance.collector_server:
                    instance.collector_server.shutdown()
                    instance.collector_server.server_close()

                # Wait for thread to finish
                if instance.collector_thread:
                    instance.collector_thread.join(timeout=5.0)

                # Unregister metrics
                for attr_name in dir(instance):
                    attr = getattr(instance, attr_name, None)
                    if isinstance(attr, (Counter, Gauge)):
                        try:
                            REGISTRY.unregister(attr)
                        except Exception as e:
                            logger.debug(
                                f"Metric {attr_name} already unregistered or failed: {e}"
                            )

                logger.info(
                    f"[rank {instance.rank}]: Prometheus metrics collector stopped and cleaned up"
                )
            except Exception as e:
                logger.error(f"Error during cleanup: {e}")
            finally:
                cls._instance = None
                cls._shutting_down = False
