# SPDX-FileCopyrightText: 2025 Qingcheng.AI
#
# SPDX-License-Identifier: Apache-2.0

import threading
import logging
import time
from typing import Optional, Dict, Tuple
from collections import defaultdict
from chitu.backend import Backend

from prometheus_client import Counter, Gauge, start_http_server

logger = logging.getLogger(__name__)


class PrometheusMetricsCollector:
    """Singleton metrics collector for Prometheus with local rate calculation"""

    _instance: Optional["PrometheusMetricsCollector"] = None
    _lock = threading.Lock()

    def __init__(self, port: int = 8000, start_server: bool = True):
        self.port = port
        self.tokens_generated_total: Optional[Counter] = None
        self.prompt_tokens_total: Optional[Counter] = None
        self.kv_cache_usage: Optional[Gauge] = None
        self.task_evictions_total: Optional[Counter] = None

        self._last_values: Dict[Tuple[int, int, str], float] = defaultdict(float)
        self._last_timestamp: Dict[Tuple[int, int, str], float] = defaultdict(float)

        self._local_deltas_lock = threading.Lock()
        self._local_tokens_generated: Dict[Tuple[int, int], int] = defaultdict(int)
        self._local_prompt_tokens: Dict[Tuple[int, int], int] = defaultdict(int)

        try:
            self.tokens_generated_total = Counter(
                "chitu_tokens_generated_total",
                "Total tokens generated by executor",
                ["rank", "dp_id"],
            )
            self.prompt_tokens_total = Counter(
                "chitu_prompt_tokens_total",
                "Total prompt tokens processed by executor",
                ["rank", "dp_id"],
            )
            self.kv_cache_usage = Gauge(
                "chitu_kv_cache_usage_ratio",
                "KV cache usage ratio (used_blocks / total_blocks)",
            )
            self.task_evictions_total = Counter(
                "chitu_task_evictions_total",
                "Total number of tasks evicted due to insufficient KV cache",
            )
            if start_server:
                start_http_server(port)
                logger.info(f"Prometheus metrics server started on port {port}")
        except Exception as e:
            logger.error(f"Failed to start Prometheus metrics server: {e}")

    @classmethod
    def get_instance(cls, port: int = 8000, start_server: bool = False):
        if cls._instance is None:
            with cls._lock:
                if cls._instance is None:
                    cls._instance = cls(port, start_server)
        return cls._instance

    def inc_tokens_generated(self, count: int = 1, rank: int = 0, dp_id: int = 0):
        with self._local_deltas_lock:
            self._local_tokens_generated[(rank, dp_id)] += count

    def inc_prompt_tokens(self, count: int = 1, rank: int = 0, dp_id: int = 0):
        with self._local_deltas_lock:
            self._local_prompt_tokens[(rank, dp_id)] += count

    @classmethod
    def inc_tokens(cls, count: int, executor):
        """Simplified method to increment tokens, automatically extracts rank and dp_id from executor"""
        try:
            collector = cls.get_instance()
            if not collector:
                return

            rank = executor.rank
            dp_id = 0
            if executor.dp_dispatcher is not None and hasattr(
                executor.dp_dispatcher, "rank_in_group"
            ):
                dp_id = executor.dp_dispatcher.rank_in_group

            collector.inc_tokens_generated(count=count, rank=rank, dp_id=dp_id)
        except Exception:
            pass

    @classmethod
    def inc_prompts(cls, count: int, executor):
        """Simplified method to increment prompt tokens, automatically extracts rank and dp_id from executor"""
        try:
            collector = cls.get_instance()
            if not collector:
                return

            rank = executor.rank
            dp_id = 0
            if executor.dp_dispatcher is not None and hasattr(
                executor.dp_dispatcher, "rank_in_group"
            ):
                dp_id = executor.dp_dispatcher.rank_in_group

            collector.inc_prompt_tokens(count=count, rank=rank, dp_id=dp_id)
        except Exception:
            pass

    def _flush_local_deltas_if_needed(self):
        # Each rank independently flushes its local metrics to Prometheus
        deltas = self.get_and_reset_local_deltas()
        self.apply_remote_deltas(deltas)

    def get_rate(self, interval_sec: float = 1.0) -> tuple[float, float, float]:
        """Calculate token generation rate, prompt rate, and eviction rate over the specified interval

        Returns:
            (prompt_rate, generation_rate, eviction_rate) in tokens/s or evictions/s, returns 0.0 if no data available
        """
        try:
            self._flush_local_deltas_if_needed()

            now = time.time()
            generation_rate = 0.0
            prompt_rate = 0.0
            eviction_rate = 0.0

            # Calculate generation rate
            if self.tokens_generated_total:
                for sample in self.tokens_generated_total.collect()[0].samples:
                    if sample.name.endswith("_created"):
                        continue
                    labels = sample.labels
                    key = (
                        int(labels.get("rank", 0)),
                        int(labels.get("dp_id", 0)),
                        "gen",
                    )
                    current_value = sample.value

                    last_value = self._last_values[key]
                    last_ts = self._last_timestamp[key]

                    if last_ts > 0:
                        elapsed = now - last_ts
                        if elapsed > 0:
                            rate = (current_value - last_value) / elapsed
                            generation_rate += rate

                    self._last_values[key] = current_value
                    self._last_timestamp[key] = now

            # Calculate prompt rate
            if self.prompt_tokens_total:
                for sample in self.prompt_tokens_total.collect()[0].samples:
                    if sample.name.endswith("_created"):
                        continue
                    labels = sample.labels
                    key = (
                        int(labels.get("rank", 0)),
                        int(labels.get("dp_id", 0)),
                        "prompt",
                    )
                    current_value = sample.value

                    last_value = self._last_values[key]
                    last_ts = self._last_timestamp[key]

                    if last_ts > 0:
                        elapsed = now - last_ts
                        if elapsed > 0:
                            rate = (current_value - last_value) / elapsed
                            prompt_rate += rate

                    self._last_values[key] = current_value
                    self._last_timestamp[key] = now

            # Calculate eviction rate
            if self.task_evictions_total:
                for sample in self.task_evictions_total.collect()[0].samples:
                    if sample.name.endswith("_created"):
                        continue
                    key = (0, 0, "eviction")
                    current_value = sample.value

                    last_value = self._last_values[key]
                    last_ts = self._last_timestamp[key]

                    if last_ts > 0:
                        elapsed = now - last_ts
                        if elapsed > 0:
                            eviction_rate = (current_value - last_value) / elapsed

                    self._last_values[key] = current_value
                    self._last_timestamp[key] = now
                    break

            return prompt_rate, generation_rate, eviction_rate
        except Exception:
            return 0.0, 0.0, 0.0

    @classmethod
    def update_metrics(cls):
        """Update KV cache usage metrics."""
        if not cls._instance:
            return

        if Backend.cache_manager is None:
            return

        num_blocks = (
            Backend.cache_manager.get_num_blocks()
            * Backend.cache_manager.get_block_size()
        )
        num_used = 0
        for _, v in Backend.cache_manager.req_id_to_seq_len.items():
            num_used += v

        if num_blocks > 0:
            usage_ratio = num_used / num_blocks
            cls._instance.kv_cache_usage.set(usage_ratio)

    @classmethod
    def inc_task_eviction(cls):
        """Increment task eviction counter"""
        if not cls._instance:
            return

        try:
            cls._instance.task_evictions_total.inc()
        except Exception:
            pass

    def get_and_reset_local_deltas(self) -> Dict:
        with self._local_deltas_lock:
            deltas = {
                "tokens_generated": dict(self._local_tokens_generated),
                "prompt_tokens": dict(self._local_prompt_tokens),
            }
            self._local_tokens_generated.clear()
            self._local_prompt_tokens.clear()
        return deltas

    def apply_remote_deltas(self, deltas: Dict):
        if not self.tokens_generated_total or not self.prompt_tokens_total:
            return

        for (rank, dp_id), count in deltas.get("tokens_generated", {}).items():
            if count > 0:
                self.tokens_generated_total.labels(rank=rank, dp_id=dp_id).inc(count)

        for (rank, dp_id), count in deltas.get("prompt_tokens", {}).items():
            if count > 0:
                self.prompt_tokens_total.labels(rank=rank, dp_id=dp_id).inc(count)
