# SPDX-FileCopyrightText: 2025 Qingcheng.AI
#
# SPDX-License-Identifier: Apache-2.0

import logging
import os
import threading
from typing import Optional
from chitu.backend import Backend
from chitu.utils import get_local_ip, get_free_port
from prometheus_client import Counter, Gauge, start_http_server, REGISTRY
import atexit
from chitu.distributed.parallel_state import get_dp_group
import torch

logger = logging.getLogger(__name__)

_pynvml = None
_pynvml_failed = False


def _import_pynvml():
    global _pynvml, _pynvml_failed
    if _pynvml_failed:
        return None
    if _pynvml is not None:
        return _pynvml
    try:
        import pynvml  # type: ignore
    except Exception:
        _pynvml_failed = True
        return None
    _pynvml = pynvml
    return _pynvml


def _nvml_handle_for_device(pynvml, device_index: int):
    cuda_visible_devices = os.environ.get("CUDA_VISIBLE_DEVICES")
    if cuda_visible_devices:
        device_tokens = [
            token.strip() for token in cuda_visible_devices.split(",") if token.strip()
        ]
        if device_index < len(device_tokens):
            token = device_tokens[device_index]
            if token.startswith(("GPU-", "MIG-")):
                return pynvml.nvmlDeviceGetHandleByUUID(token)
            try:
                return pynvml.nvmlDeviceGetHandleByIndex(int(token))
            except ValueError:
                pass
    return pynvml.nvmlDeviceGetHandleByIndex(device_index)


def _get_nvml_memory_bytes(device_index: int, pid: int):
    pynvml = _import_pynvml()
    if pynvml is None:
        return None
    initialized = False
    try:
        pynvml.nvmlInit()
        initialized = True
        handle = _nvml_handle_for_device(pynvml, device_index)
        mem_info = pynvml.nvmlDeviceGetMemoryInfo(handle)
        total = int(mem_info.total)
        used = int(mem_info.used)
        try:
            processes = pynvml.nvmlDeviceGetComputeRunningProcesses(handle)
        except Exception:
            try:
                processes = pynvml.nvmlDeviceGetComputeRunningProcesses_v2(handle)
            except Exception:
                processes = []
        for proc in processes:
            if proc.pid != pid:
                continue
            proc_used = getattr(proc, "usedGpuMemory", None)
            if proc_used is not None and proc_used > 0:
                used = int(proc_used)
            break
        return used, total
    except Exception:
        return None
    finally:
        if initialized:
            try:
                pynvml.nvmlShutdown()
            except Exception:
                pass


class PrometheusMetricsCollector:
    """Singleton metrics collector for Prometheus"""

    _instance: Optional["PrometheusMetricsCollector"] = None
    _lock = threading.RLock()
    _shutting_down = False  # 正在关闭为True，未关闭和关闭完成为False

    @classmethod
    def get_instance(cls, is_create: bool = False):
        if cls._shutting_down:
            return None

        if cls._instance is not None:
            return cls._instance

        if not is_create:
            return None

        with cls._lock:
            if cls._instance is None:
                dp_id = get_dp_group().rank_in_group
                rank = get_dp_group().global_rank
                cls._instance = cls(rank, dp_id)
        return cls._instance

    def __init__(self, rank, dp_id):
        self.rank = rank
        self.dp_id = dp_id
        self.total_generated_tokens: Optional[Counter] = None
        self.total_prompt_tokens: Optional[Counter] = None
        self.total_task_evictions: Optional[Counter] = None
        self.kv_cache_usage: Optional[Gauge] = None
        self.used_blocks: Optional[Gauge] = None
        self.total_blocks: Optional[Gauge] = None
        self.total_bytes: Optional[Gauge] = None
        self.used_bytes: Optional[Gauge] = None
        self.torch_allocated_bytes: Optional[Gauge] = None
        self.collector_server = None
        self.collector_thread = None
        self.addr = None

        try:
            self.total_generated_tokens = Counter(
                "chitu_total_generated_tokens",
                "Total tokens generated by executor",
                ["rank", "dp_id"],
            )
            self.total_prompt_tokens = Counter(
                "chitu_total_prompt_tokens",
                "Total prompt tokens processed by executor",
                ["rank", "dp_id"],
            )
            self.total_task_evictions = Counter(
                "chitu_total_task_evictions",
                "Total number of tasks evicted due to insufficient KV cache",
                ["rank", "dp_id"],
            )
            self.kv_cache_usage = Gauge(
                "chitu_kv_cache_usage_ratio",
                "KV cache usage ratio (used_blocks / total_blocks)",
                ["rank", "dp_id"],
            )
            self.used_blocks = Gauge(
                "chitu_used_blocks",
                "KV cache used blocks",
                ["rank", "dp_id"],
            )
            self.total_blocks = Gauge(
                "chitu_total_blocks",
                "KV cache total blocks",
                ["rank", "dp_id"],
            )
            self.total_bytes = Gauge(
                "chitu_total_bytes",
                "GPU total memory (bytes)",
                ["rank", "dp_id"],
            )
            self.used_bytes = Gauge(
                "chitu_used_bytes",
                "GPU used memory (bytes)",
                ["rank", "dp_id"],
            )
            self.torch_allocated_bytes = Gauge(
                "chitu_torch_allocated_bytes",
                "torch allocated GPU used memory (bytes)",
                ["rank", "dp_id"],
            )
            self.total_generated_tokens.labels(rank=rank, dp_id=dp_id).inc(0)
            self.total_prompt_tokens.labels(rank=rank, dp_id=dp_id).inc(0)
            self.total_task_evictions.labels(rank=rank, dp_id=dp_id).inc(0)
            self.kv_cache_usage.labels(rank=rank, dp_id=dp_id).set(0)
            self.used_blocks.labels(rank=rank, dp_id=dp_id).set(0)
            self.total_blocks.labels(rank=rank, dp_id=dp_id).set(0)
            self.total_bytes.labels(rank=rank, dp_id=dp_id).set(0)
            self.used_bytes.labels(rank=rank, dp_id=dp_id).set(0)
            self.torch_allocated_bytes.labels(rank=rank, dp_id=dp_id).set(0)
            try:
                ip = get_local_ip()
            except Exception:
                ip = "127.0.0.1"
            port = get_free_port()
            self.collector_server, self.collector_thread = start_http_server(
                port
            )  # Prometheus serve pull data from this server
            self.addr = f"{ip}:{port}"
            logger.info(f"Prometheus metrics server started on addr {self.addr}")
            atexit.register(PrometheusMetricsCollector.stop_instance)

        except Exception as e:
            logger.error(f"Failed to start Prometheus metrics server: {e}")
            raise

    @classmethod
    def inc_generated_tokens(cls, count: int = 1):
        if count < 0:
            return

        collector = cls.get_instance()
        if not collector:
            return
        try:
            collector.total_generated_tokens.labels(
                rank=collector.rank, dp_id=collector.dp_id
            ).inc(count)
        except Exception as e:
            logger.error(f"inc_generated_tokens failed: {e}")

    @classmethod
    def inc_prompt_tokens(cls, count: int = 1):
        if count < 0:
            return

        collector = cls.get_instance()
        if not collector:
            return
        try:
            collector.total_prompt_tokens.labels(
                rank=collector.rank, dp_id=collector.dp_id
            ).inc(count)
        except Exception as e:
            logger.error(f"inc_prompt_tokens failed: {e}")

    @classmethod
    def update_kvcache_usage(cls):
        """Update KV cache usage metrics."""
        if Backend.cache_managers is None:
            return

        cls.update_GPU_usage()

        collector = cls.get_instance()
        if not collector:
            return

        try:
            num_blocks = Backend.cache_managers["main"].get_num_blocks()
            num_used_blocks = Backend.cache_managers["main"].num_used_blocks

            collector.total_blocks.labels(
                rank=collector.rank, dp_id=collector.dp_id
            ).set(num_blocks)
            collector.used_blocks.labels(
                rank=collector.rank, dp_id=collector.dp_id
            ).set(num_used_blocks)

            if num_blocks > 0:
                usage_ratio = num_used_blocks / num_blocks
                collector.kv_cache_usage.labels(
                    rank=collector.rank, dp_id=collector.dp_id
                ).set(usage_ratio)
            else:
                logger.error(
                    f"Unexpected {type(Backend.cache_managers['main']).__name__}.num_blocks({num_blocks}), update_kvcache_usage failed. "
                )
        except Exception as e:
            logger.error(f"update_kvcache_usage failed: {e}")
            pass

    @classmethod
    def update_GPU_usage(cls):
        if Backend.cache_managers is None:
            return

        collector = cls.get_instance()
        if not collector:
            return

        try:
            device = Backend.cache_managers["main"].device
            if (not isinstance(device, torch.device)) or (
                isinstance(device, torch.device) and device.type != "cuda"
            ):
                return

            device_index = device.index
            if device_index is None:
                device_index = torch.cuda.current_device()
            mem_info = _get_nvml_memory_bytes(device_index, os.getpid())
            if mem_info is not None:
                used_bytes, total_bytes = mem_info
            else:
                free_bytes, total_bytes = torch.cuda.mem_get_info(device_index)
                used_bytes = total_bytes - free_bytes
            torch_allocated = torch.cuda.memory_allocated(device_index)
            collector.total_bytes.labels(
                rank=collector.rank, dp_id=collector.dp_id
            ).set(total_bytes)
            collector.used_bytes.labels(rank=collector.rank, dp_id=collector.dp_id).set(
                used_bytes
            )
            collector.torch_allocated_bytes.labels(
                rank=collector.rank, dp_id=collector.dp_id
            ).set(torch_allocated)

        except Exception as e:
            logger.error(f"update_GPU_usage failed: {e}")
            pass

    @classmethod
    def inc_task_eviction(cls):
        """Increment task eviction counter"""
        collector = cls.get_instance()
        if not collector:
            return

        try:
            collector.total_task_evictions.labels(
                rank=collector.rank, dp_id=collector.dp_id
            ).inc()
        except Exception as e:
            logger.error(f"inc_task_eviction failed: {e}")
            pass

    @classmethod
    def stop_instance(cls):
        cls._shutting_down = True
        with cls._lock:
            if cls._instance is None:
                return

            instance = cls._instance
            try:
                # Stop HTTP server
                if instance.collector_server:
                    instance.collector_server.shutdown()
                    instance.collector_server.server_close()

                # Wait for thread to finish
                if instance.collector_thread:
                    instance.collector_thread.join(timeout=5.0)

                # Unregister metrics
                for attr_name in dir(instance):
                    attr = getattr(instance, attr_name, None)
                    if isinstance(attr, (Counter, Gauge)):
                        try:
                            REGISTRY.unregister(attr)
                        except Exception as e:
                            logger.debug(
                                f"Metric {attr_name} already unregistered or failed: {e}"
                            )

                logger.info(
                    f"[rank {instance.rank}]: Prometheus metrics collector stopped and cleaned up"
                )
            except Exception as e:
                logger.error(f"Error during cleanup: {e}")
            finally:
                cls._instance = None
                cls._shutting_down = False
