# SPDX-FileCopyrightText: 2026 Qingcheng.AI
#
# SPDX-License-Identifier: Apache-2.0

"""Generate Markdown documentation for Chitu HTTP API parameters.

This script builds the FastAPI OpenAPI schema from ``chitu.serve.api_app`` and
renders ``docs/en/API_PARAMETERS.md`` and ``docs/zh/API_PARAMETERS.md``.

Run it from the repository root with::

    python3 script/generate_http_api_docs.py

Use ``--lang en`` or ``--lang zh`` to generate one language, and ``--check`` to
verify that generated files are up to date without modifying them.
"""

from __future__ import annotations

import argparse
import inspect
import json
import os
import sys
from pathlib import Path
from typing import Any, TypeGuard, get_args, get_origin

from pydantic import BaseModel
from pydantic_core import PydanticUndefined

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

os.environ["CHITU_GENERATING_DOCS"] = "1"

from chitu.serve.api_docs import (
    ENDPOINT_EXTRA_SECTIONS,
    ENDPOINT_NOTES,
    EXCLUDED_PATH_PREFIXES,
    EXTRA_SECTIONS,
    LANG,
    SECTION_ORDER,
    SECTION_TITLES,
)
from chitu.serve.api_app import app

OUT_FILES = {
    "en": ROOT / "docs/en/API_PARAMETERS.md",
    "zh": ROOT / "docs/zh/API_PARAMETERS.md",
}

GENERATED_NOTICE = {
    "en": "> This document is generated by `script/generate_http_api_docs.py`. Do not edit it manually; update the source metadata and rerun the script instead.",
    "zh": "> 本文档由 `script/generate_http_api_docs.py` 生成。请勿手动编辑；如需修改，请更新源代码中的元数据并重新运行该脚本。",
}


def _schema_components(openapi: dict[str, Any]) -> dict[str, Any]:
    return openapi.get("components", {}).get("schemas", {})


def _resolve_ref(schema: dict[str, Any], components: dict[str, Any]) -> dict[str, Any]:
    ref = schema.get("$ref")
    if not ref:
        return schema
    name = ref.rsplit("/", 1)[-1]
    return components[name]


def _request_schema(
    operation: dict[str, Any], components: dict[str, Any]
) -> dict[str, Any] | None:
    body = operation.get("requestBody", {})
    content = body.get("content", {})
    json_body = content.get("application/json", {})
    schema = json_body.get("schema")
    if not schema:
        return None
    return _resolve_ref(schema, components)


def _is_basemodel_class(value: Any) -> TypeGuard[type[BaseModel]]:
    try:
        return inspect.isclass(value) and issubclass(value, BaseModel)
    except TypeError:
        return False


def _component_key_for_model(model_cls: type[BaseModel]) -> str:
    return f"{model_cls.__module__.replace('.', '__')}__{model_cls.__name__}"


def _model_classes_from_annotation(annotation: Any) -> list[type[BaseModel]]:
    if _is_basemodel_class(annotation):
        return [annotation]

    origin = get_origin(annotation)
    if origin is None:
        return []

    classes: list[type[BaseModel]] = []
    for arg in get_args(annotation):
        classes.extend(_model_classes_from_annotation(arg))
    return classes


def _collect_model_classes(
    model_cls: type[BaseModel] | None,
    registry: dict[str, type[BaseModel]],
    seen: set[type[BaseModel]] | None = None,
) -> None:
    if not _is_basemodel_class(model_cls):
        return
    if seen is None:
        seen = set()
    if model_cls in seen:
        return
    seen.add(model_cls)

    registry.setdefault(model_cls.__name__, model_cls)
    registry.setdefault(_component_key_for_model(model_cls), model_cls)

    for field in model_cls.model_fields.values():
        for nested_cls in _model_classes_from_annotation(field.annotation):
            _collect_model_classes(nested_cls, registry, seen)


def _request_model_by_route() -> dict[tuple[str, str], type[BaseModel]]:
    models: dict[tuple[str, str], type[BaseModel]] = {}
    for route in app.routes:
        endpoint = getattr(route, "endpoint", None)
        if endpoint is None:
            continue

        model_cls = None
        for parameter in inspect.signature(endpoint).parameters.values():
            if _is_basemodel_class(parameter.annotation):
                model_cls = parameter.annotation
                break
        if model_cls is None:
            continue

        for method in getattr(route, "methods", set()) or set():
            models[(getattr(route, "path", ""), method.upper())] = model_cls
    return models


def _schema_name(schema: dict[str, Any], components: dict[str, Any]) -> str | None:
    for name, candidate in components.items():
        if candidate is schema:
            return name
    title = schema.get("title")
    return title if title in components else None


def _display_ref_name(name: str) -> str:
    # FastAPI/Pydantic disambiguates duplicate class names by prefixing module
    # paths in component keys, e.g. chitu__serve__openai_api__ToolChoiceNamedTool.
    # API docs should show the request schema object name, not the internal key.
    return name.rsplit("__", 1)[-1]


def _type_name(schema: dict[str, Any], components: dict[str, Any]) -> str:
    if "$ref" in schema:
        return f"`{_display_ref_name(schema['$ref'].rsplit('/', 1)[-1])}`"
    if "anyOf" in schema:
        non_null = [part for part in schema["anyOf"] if part.get("type") != "null"]
        parts = [_type_name(part, components) for part in non_null]
        if len(non_null) != len(schema["anyOf"]):
            parts.append("`null`")
        return " | ".join(parts)
    if "oneOf" in schema:
        return " | ".join(_type_name(part, components) for part in schema["oneOf"])
    if "const" in schema:
        return f"`{schema['const']}`"
    if "enum" in schema:
        return " | ".join(f"`{item}`" for item in schema["enum"])

    schema_type = schema.get("type")
    if schema_type == "array":
        item_type = _type_name(schema.get("items", {}), components).replace("`", "")
        return f"`list[{item_type}]`"
    if schema_type == "object":
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            value_type = _type_name(additional, components).replace("`", "")
            return f"`dict[str, {value_type}]`"
        return "`object`"
    if schema_type:
        return f"`{schema_type}`"
    return "`any`"


def _format_default_value(value: Any) -> str:
    if value is None:
        return "`null`"
    if isinstance(value, str):
        return f'`"{value}"`'
    if isinstance(value, bool):
        return f"`{str(value).lower()}`"
    if isinstance(value, BaseModel):
        value = value.model_dump(mode="json")
    if isinstance(value, (dict, list)):
        return f"`{json.dumps(value, ensure_ascii=False)}`"
    return f"`{value}`"


def _default_value(
    prop: dict[str, Any],
    required: bool,
    lang: str,
    field: Any | None = None,
) -> str:
    if required:
        return LANG[lang]["required"]
    if "default" in prop:
        return _format_default_value(prop["default"])

    if field is None:
        return "—"

    default_factory = getattr(field, "default_factory", None)
    if default_factory is list:
        return _format_default_value([])
    if default_factory is dict:
        return _format_default_value({})
    if _is_basemodel_class(default_factory):
        return _format_default_value(default_factory())

    default = getattr(field, "default", PydanticUndefined)
    if default is PydanticUndefined:
        return "—"
    return _format_default_value(default)


def _description(prop: dict[str, Any], lang: str) -> str:
    if lang == "zh":
        return prop.get("x-doc", {}).get("zh") or prop.get("description", "")
    return prop.get("description", "")


def _escape_cell(cell: str) -> str:
    return cell.replace("|", "\\|").replace("\n", "<br>")


def _table(headers: list[str], rows: list[list[str]]) -> list[str]:
    lines = ["| " + " | ".join(headers) + " |"]
    lines.append("|" + "|".join("---" for _ in headers) + "|")
    for row in rows:
        lines.append("| " + " | ".join(_escape_cell(cell) for cell in row) + " |")
    return lines


def _render_model_table(
    *,
    schema: dict[str, Any],
    components: dict[str, Any],
    lang: str,
    model_cls: type[BaseModel] | None = None,
) -> list[str]:
    labels = LANG[lang]
    properties = schema.get("properties", {})
    if not properties:
        return [labels["no_parameters"]]

    fields = {}
    if model_cls is not None:
        for field_name, field in model_cls.model_fields.items():
            fields[field_name] = field
            alias = getattr(field, "alias", None)
            if isinstance(alias, str):
                fields[alias] = field
            serialization_alias = getattr(field, "serialization_alias", None)
            if isinstance(serialization_alias, str):
                fields[serialization_alias] = field
    required = set(schema.get("required", []))
    rows = []
    for name, prop in properties.items():
        prop = _resolve_ref(prop, components)
        is_required = name in required
        rows.append(
            [
                f"`{name}`",
                _type_name(prop, components),
                _default_value(prop, is_required, lang, fields.get(name)),
                _description(prop, lang),
            ]
        )
    return _table(
        [labels["field"], labels["type"], labels["default"], labels["description"]],
        rows,
    )


def _route_groups(
    openapi: dict[str, Any]
) -> dict[str, list[tuple[str, str, dict[str, Any]]]]:
    groups = {section: [] for section in SECTION_ORDER}
    for path, path_item in openapi.get("paths", {}).items():
        if any(path.startswith(prefix) for prefix in EXCLUDED_PATH_PREFIXES):
            continue
        for method, operation in path_item.items():
            if method not in {"get", "post", "put", "patch", "delete"}:
                continue
            tags = operation.get("tags") or []
            section = tags[0] if tags else None
            if section in groups:
                groups[section].append((path, method.upper(), operation))
    return groups


def _operation_title(operation: dict[str, Any], lang: str) -> str:
    if lang == "zh":
        return operation.get("x-doc", {}).get("zh-summary") or operation.get(
            "summary", ""
        )
    return operation.get("summary", "")


def _operation_description(operation: dict[str, Any], lang: str) -> str:
    if lang == "zh":
        return operation.get("x-doc", {}).get("zh-description") or operation.get(
            "description", ""
        )
    return operation.get("description", "")


def _render_endpoint(
    *,
    path: str,
    method: str,
    operation: dict[str, Any],
    components: dict[str, Any],
    lang: str,
    request_models: dict[tuple[str, str], type[BaseModel]],
) -> list[str]:
    labels = LANG[lang]
    title = _operation_title(operation, lang)
    description = _operation_description(operation, lang)
    lines = [f"### {title or f'{method} {path}'}", ""]
    lines.extend(
        [f"**{labels['endpoint']}**", "", f"````text\n{method} {path}\n````", ""]
    )
    if description:
        lines.extend([description, ""])

    schema = _request_schema(operation, components)
    if schema is not None:
        root_model_cls = request_models.get((path, method))
        model_registry: dict[str, type[BaseModel]] = {}
        _collect_model_classes(root_model_cls, model_registry)
        model_name = _schema_name(schema, components)
        model_cls = model_registry.get(model_name or "")
        model_name = _display_ref_name(model_name) if model_name else None
        heading = (
            f"#### {labels['parameters_object'].format(model=model_name)}"
            if model_name
            else f"#### {labels['parameters']}"
        )
        lines.extend([heading, ""])
        lines.extend(
            _render_model_table(
                schema=schema,
                components=components,
                lang=lang,
                model_cls=model_cls,
            )
        )
        lines.append("")
    else:
        lines.extend([labels["no_parameters"], ""])

    for model_name in (
        _nested_model_names(schema, components) if schema is not None else []
    ):
        model_schema = components[model_name]
        title = labels["model_object"].format(model=_display_ref_name(model_name))
        lines.extend([f"#### {title}", ""])
        lines.extend(
            _render_model_table(
                schema=model_schema,
                components=components,
                lang=lang,
                model_cls=model_registry.get(model_name),
            )
        )
        lines.append("")

    for section in ENDPOINT_EXTRA_SECTIONS.get(path, []):
        lines.extend(_render_extra_section(section, lang, level=4))

    for note in ENDPOINT_NOTES.get(path, []):
        lines.extend([note[lang], ""])
    return lines


def _iter_ref_names(schema: dict[str, Any]) -> list[str]:
    names = []
    if "$ref" in schema:
        names.append(schema["$ref"].rsplit("/", 1)[-1])
    for key in ("anyOf", "oneOf", "allOf"):
        for part in schema.get(key, []):
            names.extend(_iter_ref_names(part))
    if "items" in schema:
        names.extend(_iter_ref_names(schema["items"]))
    additional = schema.get("additionalProperties")
    if isinstance(additional, dict):
        names.extend(_iter_ref_names(additional))
    for prop in schema.get("properties", {}).values():
        names.extend(_iter_ref_names(prop))
    return names


def _nested_model_names(
    root_schema: dict[str, Any],
    components: dict[str, Any],
) -> list[str]:
    root_name = _schema_name(root_schema, components)
    seen = {root_name} if root_name else set()
    ordered = []

    def visit(schema: dict[str, Any]):
        for ref_name in _iter_ref_names(schema):
            if ref_name in seen:
                continue
            seen.add(ref_name)
            component = components.get(ref_name)
            if not component or not component.get("properties"):
                continue
            ordered.append(ref_name)
            visit(component)

    visit(root_schema)
    return ordered


def _render_extra_section(
    section: dict[str, Any], lang: str, level: int = 2
) -> list[str]:
    lines = [f"{'#' * level} {section['title'][lang]}", ""]
    if section["type"] == "table":
        lines.extend(
            _table(section["headers"][lang], [row[lang] for row in section["rows"]])
        )
        lines.append("")
    elif section["type"] == "bullets":
        for item in section["items"]:
            lines.append(f"- {item[lang]}")
        lines.append("")
    return lines


def render(lang: str) -> str:
    openapi = app.openapi()
    components = _schema_components(openapi)
    groups = _route_groups(openapi)
    request_models = _request_model_by_route()
    labels = LANG[lang]
    lines = [
        f"# {labels['title']}",
        "",
        GENERATED_NOTICE[lang],
        "",
        labels["intro"],
        "",
    ]

    for section in SECTION_ORDER:
        routes = groups.get(section) or []
        if not routes:
            continue
        lines.extend([f"## {SECTION_TITLES[section][lang]}", ""])
        for path, method, operation in routes:
            lines.extend(
                _render_endpoint(
                    path=path,
                    method=method,
                    operation=operation,
                    components=components,
                    lang=lang,
                    request_models=request_models,
                )
            )

    for section in EXTRA_SECTIONS:
        lines.extend(_render_extra_section(section, lang, level=2))

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate HTTP API parameter docs.")
    parser.add_argument("--lang", choices=["en", "zh"], action="append")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    langs = args.lang or ["en", "zh"]
    failed = False
    for lang in langs:
        content = render(lang)
        output = OUT_FILES[lang]
        if args.check:
            if not output.exists() or output.read_text() != content:
                print(
                    f"{output} is out of date. Please run: python3 script/generate_http_api_docs.py",
                    file=sys.stderr,
                )
                failed = True
        else:
            output.write_text(content)
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
