# SPDX-FileCopyrightText: 2026 Qingcheng.AI
#
# SPDX-License-Identifier: Apache-2.0

"""Generate Markdown documentation for Chitu metrics."""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

os.environ.setdefault("CHITU_GENERATING_DOCS", "1")

from chitu.metrics.definitions import (  # noqa: E402
    DERIVED_METRICS,
    RAW_METRICS,
    DerivedMetricDefinition,
    MetricDefinition,
    MetricType,
    histogram_series_names,
    prometheus_query_name,
    validate_metric_definitions,
)

OUT_FILES = {
    "en": ROOT / "docs/en/METRICS.md",
    "zh": ROOT / "docs/zh/METRICS.md",
}

GENERATED_NOTICE = {
    "en": "> This document is generated by `script/generate_metrics_docs.py`. Do not edit it manually; update `chitu/metrics/definitions.py` and rerun the script instead.",
    "zh": "> 本文档由 `script/generate_metrics_docs.py` 生成。请勿手动编辑；如需修改，请更新 `chitu/metrics/definitions.py` 并重新运行该脚本。",
}

TEXT = {
    "en": {
        "title": "# Chitu Metrics",
        "overview_title": "## Overview",
        "overview": "Chitu exposes Prometheus metrics for debugging throughput, request latency, KV cache usage, accelerator memory, PD disaggregation, and error conditions. Raw and derived metrics are defined in a typed Python registry, and this document is generated from that registry.",
        "notes_title": "## Naming and Type Notes",
        "notes": (
            "Python Prometheus client counter query names use a `_total` suffix. "
            "For example, `chitu_total_generated_tokens` is queried as `chitu_total_generated_tokens_total`, "
            "while `chitu_completed_requests_total` keeps that query name because it already has the suffix. "
            "Histograms expose `_bucket`, `_count`, and `_sum` series. Ratio metrics use values from 0 to 1."
        ),
        "raw_title": "## Raw Metrics",
        "derived_title": "## Derived Metrics",
        "maintenance_title": "## Maintenance",
        "maintenance": "Update `chitu/metrics/definitions.py`, then run `python3 script/generate_metrics_docs.py`. Use `python3 script/generate_metrics_docs.py --check` in CI to verify these files are up to date. The generator only imports metric definitions and does not start Chitu, Prometheus, Grafana, model loading, or distributed runtime components.",
        "type": "Type",
        "query": "Prometheus query name",
        "labels": "Labels",
        "unit": "Unit",
        "scope": "Scope",
        "stdout": "Stdout",
        "grafana": "Grafana",
        "expression": "Expression",
        "source": "Source metrics",
        "yes": "yes",
        "no": "no",
        "none": "none",
        "histogram_series": "Prometheus also exposes",
        "property": "Property",
        "value": "Value",
    },
    "zh": {
        "title": "# Chitu 指标",
        "overview_title": "## 概览",
        "overview": "Chitu 暴露 Prometheus 指标，用于调试吞吐、请求延迟、KV cache 使用率、加速器显存、PD 分离和错误情况。原始指标和派生指标定义在带类型的 Python registry 中，本文档由该 registry 生成。",
        "notes_title": "## 命名和类型说明",
        "notes": (
            "Python Prometheus client 创建的 Counter 查询名会使用 `_total` 后缀。"
            "例如，`chitu_total_generated_tokens` 的查询名为 `chitu_total_generated_tokens_total`，"
            "而 `chitu_completed_requests_total` 因为已经带有该后缀，查询名保持不变。"
            "Histogram 会暴露 `_bucket`、`_count` 和 `_sum` 序列。Ratio 指标的取值范围为 0 到 1。"
        ),
        "raw_title": "## 原始指标",
        "derived_title": "## 派生指标",
        "maintenance_title": "## 维护方式",
        "maintenance": "更新 `chitu/metrics/definitions.py` 后运行 `python3 script/generate_metrics_docs.py`。在 CI 中可使用 `python3 script/generate_metrics_docs.py --check` 检查文档是否已同步。生成器只导入指标定义，不会启动 Chitu、Prometheus、Grafana、模型加载或分布式运行时组件。",
        "type": "类型",
        "query": "Prometheus 查询名",
        "labels": "标签",
        "unit": "单位",
        "scope": "范围",
        "stdout": "Stdout",
        "grafana": "Grafana",
        "expression": "表达式",
        "source": "来源指标",
        "yes": "是",
        "no": "否",
        "none": "无",
        "histogram_series": "Prometheus 还会暴露",
        "property": "属性",
        "value": "值",
    },
}


CATEGORY_TEXT = {
    "zh": {
        "Throughput": "吞吐",
        "Requests": "请求",
        "KV cache": "KV cache",
        "Memory": "显存",
        "PD disaggregation": "PD 分离",
        "Errors and timeouts": "错误和超时",
    }
}


def _category(value: object, lang: str = "en") -> str:
    category = getattr(value, "value", str(value))
    return CATEGORY_TEXT.get(lang, {}).get(category, category)


def _scope(value: object) -> str:
    return getattr(value, "value", str(value))


def _bool(value: bool, lang: str) -> str:
    return TEXT[lang]["yes"] if value else TEXT[lang]["no"]


def _raw_help(metric: MetricDefinition, lang: str) -> str:
    return metric.help_zh if lang == "zh" else metric.help_en


def _derived_help(metric: DerivedMetricDefinition, lang: str) -> str:
    return metric.help_zh if lang == "zh" else metric.help_en


def _labels(metric: MetricDefinition, lang: str) -> str:
    return ", ".join(f"`{label}`" for label in metric.labels) or TEXT[lang]["none"]


def _property_table(lang: str, rows: list[tuple[str, str]]) -> list[str]:
    t = TEXT[lang]
    lines = [
        f"| {t['property']} | {t['value']} |",
        "|---|---|",
    ]
    lines.extend(f"| {name} | {value} |" for name, value in rows)
    return lines


def _raw_metric_lines(metric: MetricDefinition, lang: str) -> list[str]:
    t = TEXT[lang]
    rows = [
        (t["type"], f"`{metric.type.value}`"),
        (t["query"], f"`{prometheus_query_name(metric)}`"),
        (t["labels"], _labels(metric, lang)),
        (t["unit"], metric.unit or t["none"]),
        (t["scope"], f"`{_scope(metric.scope)}`"),
        (t["stdout"], _bool(metric.stdout, lang)),
        (t["grafana"], _bool(metric.grafana, lang)),
    ]
    if metric.type == MetricType.HISTOGRAM:
        series = ", ".join(f"`{name}`" for name in histogram_series_names(metric))
        rows.append((t["histogram_series"], series))
    lines = [
        f"#### `{prometheus_query_name(metric)}`",
        "",
        _raw_help(metric, lang),
        "",
        *_property_table(lang, rows),
        "",
    ]
    return lines


def _raw_details(lang: str) -> list[str]:
    lines: list[str] = []
    for category in sorted(
        {_category(metric.category, lang) for metric in RAW_METRICS}
    ):
        lines.extend(["", f"### {category}", ""])
        for metric in [
            m for m in RAW_METRICS if _category(m.category, lang) == category
        ]:
            lines.extend(_raw_metric_lines(metric, lang))
    return lines


def _derived_metric_lines(metric: DerivedMetricDefinition, lang: str) -> list[str]:
    t = TEXT[lang]
    source = ", ".join(f"`{name}`" for name in metric.source_metrics)
    rows = [
        (t["expression"], f"`{metric.expression}`"),
        (t["source"], source),
        (t["scope"], f"`{_scope(metric.scope)}`"),
        (t["stdout"], _bool(metric.stdout, lang)),
        (t["grafana"], _bool(metric.grafana, lang)),
    ]
    lines = [
        f"#### `{metric.name}`",
        "",
        _derived_help(metric, lang),
        "",
        *_property_table(lang, rows),
        "",
    ]
    return lines


def _derived_details(lang: str) -> list[str]:
    lines: list[str] = []
    for category in sorted(
        {_category(metric.category, lang) for metric in DERIVED_METRICS}
    ):
        lines.extend(["", f"### {category}", ""])
        for metric in [
            m for m in DERIVED_METRICS if _category(m.category, lang) == category
        ]:
            lines.extend(_derived_metric_lines(metric, lang))
    return lines


def render(lang: str) -> str:
    t = TEXT[lang]
    lines = [
        t["title"],
        "",
        GENERATED_NOTICE[lang],
        "",
        t["overview_title"],
        "",
        t["overview"],
        "",
        t["notes_title"],
        "",
        t["notes"],
        "",
        t["raw_title"],
        *_raw_details(lang),
        t["derived_title"],
        *_derived_details(lang),
        t["maintenance_title"],
        "",
        t["maintenance"],
        "",
    ]
    return "\n".join(lines)


def _read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return ""


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="Only check generated docs"
    )
    parser.add_argument(
        "--print", choices=("en", "zh"), help="Print one language to stdout"
    )
    args = parser.parse_args()

    validation_errors = validate_metric_definitions()
    if validation_errors:
        print("Metric definitions are invalid:", file=sys.stderr)
        for error in validation_errors:
            print(f"  - {error}", file=sys.stderr)
        return 1

    rendered = {lang: render(lang) for lang in OUT_FILES}

    if args.print:
        print(rendered[args.print])
        return 0

    changed = any(_read(path) != rendered[lang] for lang, path in OUT_FILES.items())
    if args.check:
        if changed:
            print(
                "Metrics docs are outdated. Please run:\n  python3 script/generate_metrics_docs.py",
                file=sys.stderr,
            )
            return 2
        print("Metrics docs are up-to-date.")
        return 0

    for lang, path in OUT_FILES.items():
        if _read(path) != rendered[lang]:
            _write(path, rendered[lang])
    print("Updated metrics docs." if changed else "No changes needed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
