defaults:
  # - models: qwen2-70b
  - models: qwen2-7b
  # - models: llama3-8b
serve:
  host: 0.0.0.0
  port: 21002
infer:
  tp_size: 1
  pp_size: 1
  do_load: True # set it to False for debug purpose
  seed: 0
  stop_with_eos: True
  max_seq_len: 10240 # length of prefill + decode
  cache_type: skew
  attn_type: flash # flash or ref
  op_impl: torch # torch or muxi_custom_kernel
  max_reqs: 8
request:
  prompt_tokens_len: -1 # use for perf test in single_req_test.py, -1 means use real requests.
  max_new_tokens: 128
scheduler:
  type: prefill_first
  fcfs:
    num_tasks: 16
    enable_hybrid: False
  prefill_first:
    num_tasks: 8
    enable_hybrid: False
  stride:
    num_tasks: 2
    enable_hybrid: False
  deadline:
    num_tasks: 2
    enable_hybrid: False
  prefix_align:
    num_tasks: 2
    enable_hybrid: False
  balance:
    num_tasks: 2
    enable_hybrid: False
quant: None
dtype: bfloat16
