# SPDX-FileCopyrightText: 2025 Qingcheng.AI
#
# SPDX-License-Identifier: Apache-2.0

# QwQ-32B-fp4 is a quantization of QwQ-32B
defaults:
  - DeepSeek-V3.2-Exp
  - _self_ # Config in this file overrides configs in defaults

# Access info
name: DeepSeek-V3.2
source: "https://huggingface.co/deepseek-ai/DeepSeek-V3.2" # Just for displaying. No automatic download.
chatformat_type: dsv32
tool_parser: DeepSeekV32ToolParser
skip_special_tokens: False # Whether to skip special tokens when decoding with the tokenizer
