# DeepSeek-R1-Q4_K_M is a data-type variant of DeepSeek-R1
defaults:
  - DeepSeek-V3
  - _self_ # Config in this file overrides configs in defaults

# Access info
name: DeepSeek-R1-Q4_K_M

ckpt_dir: null # Please override this in commond line with `models.ckpt_dir=<path>`.
tokenizer_path: null # By default the same as ckpt_dir, or you can override it with `models.tokenizer_path=<path>`.

# Overrides
quant: gguf
cpu_num_thread: 64
