name: DeepSeek-R1-bf16
type: deepseek-v3
source: "https://huggingface.co/opensourcerelease/DeepSeek-R1-bf16" # Just for displaying. No automatic download.
ckpt_dir: null # Please override this in commond line with `models.ckpt_dir=<path>`.
tokenizer_path: null # By default the same as ckpt_dir, or you can override it with `models.tokenizer_path=<path>`.
vocab_size: 129280
dim: 7168
inter_dim: 18432
moe_inter_dim: 2048
n_layers: 61
n_dense_layers: 3
n_heads: 128
n_routed_experts: 256
n_shared_experts: 1
n_activated_experts: 8
n_expert_groups: 8
n_limited_groups: 4
route_scale: 2.5
score_func: "sigmoid"
q_lora_rank: 1536
kv_lora_rank: 512
qk_nope_head_dim: 128
qk_rope_head_dim: 64
v_head_dim: 128
rope_theta: 10000.0
rope_factor: 40
rs_token_id: 151648
re_token_id: 151649
main_weight_dtype: bfloat16
