# SPDX-FileCopyrightText: 2026 Qingcheng.AI
#
# SPDX-License-Identifier: Apache-2.0

# GLM-5-FP8 with FP8 MLA KV cache.
defaults:
  - GLM-5-FP8
  - override quant_config: blockfp8_dsa_kv
  - _self_ # Config in this file overrides configs in defaults

name: GLM-5-FP8-kv
source: "https://huggingface.co/zai-org/GLM-5-FP8" # Just for displaying. No automatic download.
