name: Mixtral-8x7B-Instruct-v0.1
type: hf-mixtral
source: "https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1" # Just for displaying. No automatic download.
ckpt_dir: null # Please override this in commond line with `models.ckpt_dir=<path>`.
tokenizer_path: null # By default the same as ckpt_dir, or you can override it with `models.tokenizer_path=<path>`.
dim: 4096
n_layers: 32
n_heads: 32
n_kv_heads: 8
vocab_size: 32000
intermediate_dim: 14336
norm_eps: 1e-05
rope_theta: 1000000.0
num_local_experts: 8
num_experts_per_tok: 2
qkv_has_bias: false
tokenizer_force_full_seq_decode: true
