defaults:
  - Qwen3-32B
  - backend_config: mix-cpu
  - _self_ # Config in this file overrides configs in defaults

# Access info
name: Qwen3-32B-mix-cpu
source: "https://huggingface.co/Qwen/Qwen3-32B" # Just for displaying. No automatic download.
ckpt_dir: null # Please override this in commond line with `models.ckpt_dir=<path>`.
tokenizer_path: null # By default the same as ckpt_dir, or you can override it with `models.tokenizer_path=<path>`.
