name: Qwen2-72B-Instruct
type: hf-llama
source: "https://huggingface.co/Qwen/Qwen2-72B-Instruct" # Just for displaying. No automatic download.
ckpt_dir: null # Please override this in commond line with `models.ckpt_dir=<path>`.
tokenizer_path: null # By default the same as ckpt_dir, or you can override it with `models.tokenizer_path=<path>`.
dim: 8192
n_layers: 80
n_heads: 64
n_kv_heads: 8
vocab_size: 152064
intermediate_dim: 29568
norm_eps: 1e-06
rope_theta: 1000000.0
