# SPDX-FileCopyrightText: 2026 Qingcheng.AI
#
# SPDX-License-Identifier: Apache-2.0

# Qwen3.6-35B-A3B shares the same model structure with Qwen3.5-35B-A3B
defaults:
  - Qwen3.5-35B-A3B
  - _self_ # Config in this file overrides configs in defaults

# Access info
name: Qwen3.6-35B-A3B
source: "https://huggingface.co/Qwen/Qwen3.6-35B-A3B" # Just for displaying. No automatic download.
