# QwQ-32B-fp4 is a quantization of QwQ-32B
defaults:
  - QwQ-32B
  - _self_ # Config in this file overrides configs in defaults

# Access info
name: QwQ-32B-fp4
source: "(This is an internal quantized model, only for testing purpose)" # Just for displaying. No automatic download.
ckpt_dir: null # Please override this in commond line with `models.ckpt_dir=<path>`.
tokenizer_path: null # By default the same as ckpt_dir, or you can override it with `models.tokenizer_path=<path>`.

# Overrides
quant: blockfp4
